const makeSymbols = (items) =>
  items.map(([label, value, aliases = '', extra = {}]) => ({
    label,
    value,
    aliases,
    ...extra,
  }))

export const latexSymbolGroups = [
  {
    name: 'Greek lowercase',
    symbols: makeSymbols([
      ['α', '\\alpha', 'alpha'],
      ['β', '\\beta', 'beta'],
      ['γ', '\\gamma', 'gamma'],
      ['δ', '\\delta', 'delta'],
      ['ε', '\\epsilon', 'epsilon'],
      ['ε', '\\varepsilon', 'varepsilon epsilon'],
      ['ζ', '\\zeta', 'zeta'],
      ['η', '\\eta', 'eta'],
      ['θ', '\\theta', 'theta'],
      ['ϑ', '\\vartheta', 'vartheta theta'],
      ['ι', '\\iota', 'iota'],
      ['κ', '\\kappa', 'kappa'],
      ['λ', '\\lambda', 'lambda'],
      ['μ', '\\mu', 'mu'],
      ['ν', '\\nu', 'nu'],
      ['ξ', '\\xi', 'xi'],
      ['π', '\\pi', 'pi'],
      ['ϖ', '\\varpi', 'varpi pi'],
      ['ρ', '\\rho', 'rho'],
      ['ϱ', '\\varrho', 'varrho rho'],
      ['σ', '\\sigma', 'sigma'],
      ['ς', '\\varsigma', 'varsigma sigma'],
      ['τ', '\\tau', 'tau'],
      ['υ', '\\upsilon', 'upsilon'],
      ['φ', '\\phi', 'phi'],
      ['φ', '\\varphi', 'varphi phi'],
      ['χ', '\\chi', 'chi'],
      ['ψ', '\\psi', 'psi'],
      ['ω', '\\omega', 'omega'],
    ]),
  },
  {
    name: 'Greek uppercase',
    symbols: makeSymbols([
      ['Γ', '\\Gamma', 'Gamma'],
      ['Δ', '\\Delta', 'Delta'],
      ['Θ', '\\Theta', 'Theta'],
      ['Λ', '\\Lambda', 'Lambda'],
      ['Ξ', '\\Xi', 'Xi'],
      ['Π', '\\Pi', 'Pi'],
      ['Σ', '\\Sigma', 'Sigma'],
      ['Υ', '\\Upsilon', 'Upsilon'],
      ['Φ', '\\Phi', 'Phi'],
      ['Ψ', '\\Psi', 'Psi'],
      ['Ω', '\\Omega', 'Omega'],
    ]),
  },
  {
    name: 'Relations',
    symbols: makeSymbols([
      ['=', '=', 'equals'],
      ['≠', '\\ne', 'not equal neq'],
      ['≈', '\\approx', 'approximately'],
      ['≃', '\\simeq', 'simeq'],
      ['≅', '\\cong', 'congruent'],
      ['≡', '\\equiv', 'equivalent'],
      ['∼', '\\sim', 'similar'],
      ['∝', '\\propto', 'proportional'],
      ['<', '<', 'less'],
      ['>', '>', 'greater'],
      ['≤', '\\leq', 'le less equal'],
      ['≥', '\\geq', 'ge greater equal'],
      ['≪', '\\ll', 'much less'],
      ['≫', '\\gg', 'much greater'],
      ['⊂', '\\subset', 'subset'],
      ['⊃', '\\supset', 'superset'],
      ['⊆', '\\subseteq', 'subset equal'],
      ['⊇', '\\supseteq', 'superset equal'],
      ['⊄', '\\not\\subset', 'not subset'],
      ['∈', '\\in', 'in member'],
      ['∉', '\\notin', 'not in'],
      ['∋', '\\ni', 'contains member'],
      ['∥', '\\parallel', 'parallel'],
      ['∦', '\\nparallel', 'not parallel'],
      ['⊥', '\\perp', 'perpendicular'],
      ['⊢', '\\vdash', 'vdash proves'],
      ['⊨', '\\models', 'models'],
      ['≺', '\\prec', 'precedes'],
      ['≻', '\\succ', 'succeeds'],
      ['≼', '\\preceq', 'precedes equal'],
      ['≽', '\\succeq', 'succeeds equal'],
    ]),
  },
  {
    name: 'Negated and AMS relations',
    symbols: makeSymbols([
      ['≮', '\\nless', 'not less amssymb'],
      ['≯', '\\ngtr', 'not greater amssymb'],
      ['≰', '\\nleq', 'not less equal amssymb'],
      ['≱', '\\ngeq', 'not greater equal amssymb'],
      ['≨', '\\lneq', 'less not equal amssymb'],
      ['≩', '\\gneq', 'greater not equal amssymb'],
      ['≨', '\\lneqq', 'less not double equal amssymb'],
      ['≩', '\\gneqq', 'greater not double equal amssymb'],
      ['⊀', '\\nprec', 'not precedes amssymb'],
      ['⊁', '\\nsucc', 'not succeeds amssymb'],
      ['⊈', '\\nsubseteq', 'not subset equal amssymb'],
      ['⊉', '\\nsupseteq', 'not superset equal amssymb'],
      ['⊊', '\\subsetneq', 'proper subset not equal amssymb'],
      ['⊋', '\\supsetneq', 'proper superset not equal amssymb'],
      ['⊊', '\\subsetneqq', 'proper subset double not equal amssymb'],
      ['⊋', '\\supsetneqq', 'proper superset double not equal amssymb'],
      ['∤', '\\nmid', 'does not divide amssymb'],
      ['⊬', '\\nvdash', 'not proves amssymb'],
      ['⊭', '\\nvDash', 'not semantic entailment amssymb'],
      ['⊮', '\\nVdash', 'not force amssymb'],
      ['⊯', '\\nVDash', 'not double force amssymb'],
      ['⋈', '\\bowtie', 'bowtie relation'],
      ['⋈', '\\Join', 'join relation'],
      ['⌣', '\\smile', 'smile relation'],
      ['⌢', '\\frown', 'frown relation'],
      ['≍', '\\asymp', 'asymptotic relation'],
      ['≐', '\\doteq', 'dot equal'],
      ['≜', '\\triangleq', 'triangle equal'],
      ['≏', '\\bumpeq', 'bump equal amssymb'],
      ['≎', '\\Bumpeq', 'double bump equal amssymb'],
    ]),
  },
  {
    name: 'Operators',
    symbols: makeSymbols([
      ['±', '\\pm', 'plus minus'],
      ['∓', '\\mp', 'minus plus'],
      ['×', '\\times', 'times multiplication'],
      ['÷', '\\div', 'division'],
      ['·', '\\cdot', 'dot product'],
      ['∘', '\\circ', 'circle composition'],
      ['∗', '\\ast', 'asterisk'],
      ['⋆', '\\star', 'star'],
      ['∧', '\\wedge', 'and wedge'],
      ['∨', '\\vee', 'or vee'],
      ['∩', '\\cap', 'intersection'],
      ['∪', '\\cup', 'union'],
      ['⊎', '\\uplus', 'disjoint union'],
      ['⊓', '\\sqcap', 'square cap'],
      ['⊔', '\\sqcup', 'square cup'],
      ['⊕', '\\oplus', 'direct sum xor'],
      ['⊖', '\\ominus', 'ominus'],
      ['⊗', '\\otimes', 'tensor product'],
      ['⊘', '\\oslash', 'oslash'],
      ['⊙', '\\odot', 'odot'],
      ['†', '\\dagger', 'dagger'],
      ['‡', '\\ddagger', 'double dagger'],
      ['∖', '\\setminus', 'set minus'],
      ['≀', '\\wr', 'wreath'],
      ['⋄', '\\diamond', 'diamond'],
      ['△', '\\triangle', 'triangle'],
      ['◁', '\\triangleleft', 'triangle left'],
      ['▷', '\\triangleright', 'triangle right'],
    ]),
  },
  {
    name: 'More operators',
    symbols: makeSymbols([
      ['⨿', '\\amalg', 'amalgamation'],
      ['○', '\\bigcirc', 'big circle'],
      ['•', '\\bullet', 'bullet'],
      ['⋅', '\\centerdot', 'center dot amssymb'],
      ['▽', '\\bigtriangledown', 'big triangle down'],
      ['△', '\\bigtriangleup', 'big triangle up'],
      ['◁', '\\lhd', 'left triangle operator amssymb'],
      ['▷', '\\rhd', 'right triangle operator amssymb'],
      ['⊴', '\\unlhd', 'unlhd amssymb'],
      ['⊵', '\\unrhd', 'unrhd amssymb'],
      ['⊞', '\\boxplus', 'boxed plus amssymb'],
      ['⊟', '\\boxminus', 'boxed minus amssymb'],
      ['⊠', '\\boxtimes', 'boxed times amssymb'],
      ['⊡', '\\boxdot', 'boxed dot amssymb'],
      ['⊛', '\\circledast', 'circled ast amssymb'],
      ['⊚', '\\circledcirc', 'circled circ amssymb'],
      ['⊝', '\\circleddash', 'circled dash amssymb'],
      ['⋉', '\\ltimes', 'left times amssymb'],
      ['⋊', '\\rtimes', 'right times amssymb'],
      ['⋋', '\\leftthreetimes', 'left three times amssymb'],
      ['⋌', '\\rightthreetimes', 'right three times amssymb'],
      ['⋏', '\\curlywedge', 'curly wedge amssymb'],
      ['⋎', '\\curlyvee', 'curly vee amssymb'],
      ['⋒', '\\Cap', 'double cap amssymb'],
      ['⋓', '\\Cup', 'double cup amssymb'],
      ['∖', '\\smallsetminus', 'small set minus amssymb'],
      ['⊺', '\\intercal', 'intercal amssymb'],
      ['⊻', '\\veebar', 'vee bar amssymb'],
      ['⊼', '\\barwedge', 'bar wedge amssymb'],
    ]),
  },
  {
    name: 'Arrows',
    symbols: makeSymbols([
      ['←', '\\leftarrow', 'left arrow'],
      ['→', '\\rightarrow', 'right arrow'],
      ['↔', '\\leftrightarrow', 'left right arrow'],
      ['⇐', '\\Leftarrow', 'double left arrow'],
      ['⇒', '\\Rightarrow', 'double right arrow implies'],
      ['⇔', '\\Leftrightarrow', 'iff equivalent'],
      ['↦', '\\mapsto', 'mapsto'],
      ['↩', '\\hookleftarrow', 'hook left'],
      ['↪', '\\hookrightarrow', 'hook right'],
      ['↗', '\\nearrow', 'north east arrow'],
      ['↘', '\\searrow', 'south east arrow'],
      ['↙', '\\swarrow', 'south west arrow'],
      ['↖', '\\nwarrow', 'north west arrow'],
      ['↑', '\\uparrow', 'up arrow'],
      ['↓', '\\downarrow', 'down arrow'],
      ['↕', '\\updownarrow', 'up down arrow'],
      ['⇑', '\\Uparrow', 'double up arrow'],
      ['⇓', '\\Downarrow', 'double down arrow'],
      ['⇕', '\\Updownarrow', 'double up down arrow'],
      ['⟵', '\\longleftarrow', 'long left arrow'],
      ['⟶', '\\longrightarrow', 'long right arrow'],
      ['⟷', '\\longleftrightarrow', 'long left right arrow'],
      ['⟸', '\\Longleftarrow', 'long double left arrow'],
      ['⟹', '\\Longrightarrow', 'long double right arrow'],
      ['⟺', '\\Longleftrightarrow', 'long double left right arrow'],
    ]),
  },
  {
    name: 'More arrows',
    symbols: makeSymbols([
      ['↝', '\\leadsto', 'leadsto arrow amssymb'],
      ['⇝', '\\rightsquigarrow', 'right squiggle arrow amssymb'],
      ['↭', '\\leftrightsquigarrow', 'left right squiggle arrow amssymb'],
      ['↞', '\\twoheadleftarrow', 'two head left arrow amssymb'],
      ['↠', '\\twoheadrightarrow', 'two head right arrow amssymb'],
      ['⇇', '\\leftleftarrows', 'two left arrows amssymb'],
      ['⇉', '\\rightrightarrows', 'two right arrows amssymb'],
      ['⇆', '\\leftrightarrows', 'left right paired arrows amssymb'],
      ['⇄', '\\rightleftarrows', 'right left paired arrows amssymb'],
      ['⇈', '\\upuparrows', 'two up arrows amssymb'],
      ['⇊', '\\downdownarrows', 'two down arrows amssymb'],
      ['⇠', '\\dashleftarrow', 'dash left arrow amssymb'],
      ['⇢', '\\dashrightarrow', 'dash right arrow amssymb'],
      ['↢', '\\leftarrowtail', 'left arrow tail amssymb'],
      ['↣', '\\rightarrowtail', 'right arrow tail amssymb'],
      ['↫', '\\looparrowleft', 'loop left arrow amssymb'],
      ['↬', '\\looparrowright', 'loop right arrow amssymb'],
      ['↺', '\\circlearrowleft', 'circle left arrow amssymb'],
      ['↻', '\\circlearrowright', 'circle right arrow amssymb'],
      ['↰', '\\Lsh', 'L-shaped arrow amssymb'],
      ['↱', '\\Rsh', 'R-shaped arrow amssymb'],
      ['↶', '\\curvearrowleft', 'curve left arrow amssymb'],
      ['↷', '\\curvearrowright', 'curve right arrow amssymb'],
      ['⊸', '\\multimap', 'linear map arrow amssymb'],
    ]),
  },
  {
    name: 'Calculus',
    symbols: makeSymbols([
      ['∂', '\\partial', 'partial derivative'],
      ['∇', '\\nabla', 'nabla gradient'],
      ['∞', '\\infty', 'infinity'],
      ['∫', '\\int', 'integral'],
      ['∮', '\\oint', 'contour integral'],
      ['∑', '\\sum', 'sum summation'],
      ['∏', '\\prod', 'product'],
      ['∐', '\\coprod', 'coproduct'],
      ['∫∫', '\\iint', 'double integral'],
      ['∫∫∫', '\\iiint', 'triple integral'],
      ['lim', '\\lim', 'limit'],
      ['max', '\\max', 'maximum'],
      ['min', '\\min', 'minimum'],
      ['argmax', '\\arg\\max', 'arg max'],
      ['argmin', '\\arg\\min', 'arg min'],
      ['d/dx', '\\frac{d}{dx}', 'derivative'],
      ['∂/∂x', '\\frac{\\partial}{\\partial x}', 'partial derivative fraction'],
      ['√', '\\sqrt{x}', 'square root'],
      ['ⁿ√', '\\sqrt[n]{x}', 'nth root'],
      ['frac', '\\frac{a}{b}', 'fraction'],
    ]),
  },
  {
    name: 'Logic and sets',
    symbols: makeSymbols([
      ['∀', '\\forall', 'forall'],
      ['∃', '\\exists', 'exists'],
      ['∄', '\\nexists', 'not exists'],
      ['¬', '\\neg', 'not negation'],
      ['∧', '\\land', 'logical and'],
      ['∨', '\\lor', 'logical or'],
      ['⊤', '\\top', 'top true'],
      ['⊥', '\\bot', 'bottom false'],
      ['∅', '\\emptyset', 'empty set'],
      ['∅', '\\varnothing', 'varnothing'],
      ['ℕ', '\\mathbb{N}', 'naturals'],
      ['ℤ', '\\mathbb{Z}', 'integers'],
      ['ℚ', '\\mathbb{Q}', 'rationals'],
      ['ℝ', '\\mathbb{R}', 'reals'],
      ['ℂ', '\\mathbb{C}', 'complex'],
      ['ℙ', '\\mathbb{P}', 'probability projective'],
      ['ℰ', '\\mathcal{E}', 'event mathcal E'],
      ['𝒟', '\\mathcal{D}', 'dataset distribution'],
      ['𝓛', '\\mathcal{L}', 'loss lagrangian'],
      ['𝒪', '\\mathcal{O}', 'big O'],
      ['P(A)', '\\mathbb{P}(A)', 'probability'],
      ['E[X]', '\\mathbb{E}[X]', 'expectation'],
    ]),
  },
  {
    name: 'Delimiters',
    symbols: makeSymbols([
      ['( )', '\\left( x \\right)', 'parentheses'],
      ['[ ]', '\\left[ x \\right]', 'brackets'],
      ['{ }', '\\left\\{ x \\right\\}', 'braces'],
      ['| |', '\\left| x \\right|', 'absolute value'],
      ['|| ||', '\\left\\lVert x \\right\\rVert', 'norm'],
      ['⌈ ⌉', '\\left\\lceil x \\right\\rceil', 'ceil'],
      ['⌊ ⌋', '\\left\\lfloor x \\right\\rfloor', 'floor'],
      ['⟨ ⟩', '\\left\\langle x \\right\\rangle', 'angle brackets'],
      ['⟦ ⟧', '\\left\\llbracket x \\right\\rrbracket', 'semantic brackets'],
      ['⟮ ⟯', '\\lgroup x \\rgroup', 'large group'],
    ]),
  },
  {
    name: 'Accents',
    symbols: makeSymbols([
      ['◌̂', '\\hat{__BASE__}', 'hat accent apply wrap', { accent: true }],
      ['◌̃', '\\tilde{__BASE__}', 'tilde accent apply wrap', { accent: true }],
      ['◌̄', '\\bar{__BASE__}', 'bar accent apply wrap', { accent: true }],
      ['⃗', '\\vec{__BASE__}', 'vector accent apply wrap', { accent: true }],
      ['◌̇', '\\dot{__BASE__}', 'dot accent apply wrap', { accent: true }],
      ['◌̈', '\\ddot{__BASE__}', 'double dot accent apply wrap', { accent: true }],
      ['◌̆', '\\breve{__BASE__}', 'breve accent apply wrap', { accent: true }],
      ['◌̌', '\\check{__BASE__}', 'check accent apply wrap', { accent: true }],
      ['◌́', '\\acute{__BASE__}', 'acute accent apply wrap', { accent: true }],
      ['◌̀', '\\grave{__BASE__}', 'grave accent apply wrap', { accent: true }],
      ['▁', '\\underline{__BASE__}', 'underline accent apply wrap', { accent: true }],
      ['▔', '\\overline{__BASE__}', 'overline accent apply wrap', { accent: true }],
      ['◌̃', '\\widetilde{__BASE__}', 'wide tilde accent apply wrap', { accent: true }],
      ['◌̂', '\\widehat{__BASE__}', 'wide hat accent apply wrap', { accent: true }],
    ]),
  },
  {
    name: 'Misc math',
    symbols: makeSymbols([
      ['°', '^\\circ', 'degree'],
      ['′', '\\prime', 'prime'],
      ['″', "^{\\prime\\prime}", 'double prime'],
      ['∠', '\\angle', 'angle'],
      ['△', '\\triangle', 'triangle'],
      ['□', '\\square', 'square'],
      ['◇', '\\lozenge', 'lozenge'],
      ['♣', '\\clubsuit', 'clubsuit'],
      ['♢', '\\diamondsuit', 'diamondsuit'],
      ['♡', '\\heartsuit', 'heartsuit'],
      ['♠', '\\spadesuit', 'spadesuit'],
      ['ℓ', '\\ell', 'ell'],
      ['ℏ', '\\hbar', 'hbar'],
      ['ı', '\\imath', 'imath'],
      ['ȷ', '\\jmath', 'jmath'],
      ['ℜ', '\\Re', 'real part'],
      ['ℑ', '\\Im', 'imaginary part'],
      ['℘', '\\wp', 'weierstrass'],
      ['⋯', '\\cdots', 'center dots'],
      ['⋮', '\\vdots', 'vertical dots'],
      ['⋱', '\\ddots', 'diagonal dots'],
    ]),
  },
  {
    name: 'Alphabets and operators',
    symbols: makeSymbols([
      ['𝔸', '\\mathbb{A}', 'blackboard A amssymb'],
      ['𝔹', '\\mathbb{B}', 'blackboard B amssymb'],
      ['𝔻', '\\mathbb{D}', 'blackboard D amssymb'],
      ['𝔽', '\\mathbb{F}', 'blackboard F amssymb'],
      ['𝔾', '\\mathbb{G}', 'blackboard G amssymb'],
      ['ℍ', '\\mathbb{H}', 'blackboard H amssymb'],
      ['𝕀', '\\mathbb{I}', 'blackboard I amssymb'],
      ['𝕂', '\\mathbb{K}', 'blackboard K amssymb'],
      ['𝕃', '\\mathbb{L}', 'blackboard L amssymb'],
      ['𝕄', '\\mathbb{M}', 'blackboard M amssymb'],
      ['𝕆', '\\mathbb{O}', 'blackboard O amssymb'],
      ['𝕊', '\\mathbb{S}', 'blackboard S amssymb'],
      ['𝕋', '\\mathbb{T}', 'blackboard T amssymb'],
      ['𝕌', '\\mathbb{U}', 'blackboard U amssymb'],
      ['𝒜', '\\mathcal{A}', 'calligraphic A'],
      ['ℬ', '\\mathcal{B}', 'calligraphic B'],
      ['ℱ', '\\mathcal{F}', 'calligraphic F'],
      ['𝒢', '\\mathcal{G}', 'calligraphic G'],
      ['ℋ', '\\mathcal{H}', 'calligraphic H'],
      ['ℳ', '\\mathcal{M}', 'calligraphic M'],
      ['𝒩', '\\mathcal{N}', 'calligraphic N'],
      ['𝒫', '\\mathcal{P}', 'calligraphic P'],
      ['𝒮', '\\mathcal{S}', 'calligraphic S'],
      ['𝔞', '\\mathfrak{a}', 'fraktur a amssymb'],
      ['𝔤', '\\mathfrak{g}', 'fraktur g amssymb'],
      ['𝔪', '\\mathfrak{m}', 'fraktur m amssymb'],
      ['𝔭', '\\mathfrak{p}', 'fraktur p amssymb'],
      ['𝐱', '\\mathbf{x}', 'bold x'],
      ['𝛉', '\\boldsymbol{\\theta}', 'bold theta'],
      ['d', '\\mathrm{d}', 'upright differential d'],
      ['rank', '\\operatorname{rank}', 'rank operator'],
      ['diag', '\\operatorname{diag}', 'diag operator'],
      ['tr', '\\operatorname{tr}', 'trace operator'],
      ['Var', '\\operatorname{Var}', 'variance operator'],
      ['Cov', '\\operatorname{Cov}', 'covariance operator'],
    ]),
  },
  {
    name: 'Text, units, and punctuation',
    symbols: makeSymbols([
      ['%', '\\%', 'percent literal'],
      ['$', '\\$', 'dollar literal'],
      ['&', '\\&', 'ampersand literal'],
      ['#', '\\#', 'hash literal'],
      ['_', '\\_', 'underscore literal'],
      ['§', '\\S', 'section sign'],
      ['¶', '\\P', 'paragraph sign'],
      ['°', '\\textdegree', 'degree textcomp'],
      ['µ', '\\textmu', 'micro textcomp'],
      ['dB', '\\mathrm{dB}', 'decibel unit'],
      ['Hz', '\\mathrm{Hz}', 'hertz unit'],
      ['m', '\\mathrm{m}', 'meter unit'],
      ['s', '\\mathrm{s}', 'second unit'],
      ['ms', '\\mathrm{ms}', 'millisecond unit'],
      ['µm', '\\mu\\mathrm{m}', 'micrometer unit'],
      ['kg', '\\mathrm{kg}', 'kilogram unit'],
      ['W', '\\mathrm{W}', 'watt unit'],
      ['V', '\\mathrm{V}', 'volt unit'],
      ['A', '\\mathrm{A}', 'ampere unit'],
      ['Ω', '\\Omega', 'ohm unit omega'],
    ]),
  },
  {
    name: 'ML labels',
    symbols: makeSymbols([
      ['xᵢ', 'x_i', 'feature index'],
      ['yᵢ', 'y_i', 'target index'],
      ['ŷ', '\\hat{y}', 'prediction'],
      ['θ', '\\theta', 'parameter theta'],
      ['w', '\\mathbf{w}', 'weights'],
      ['b', 'b', 'bias'],
      ['L', '\\mathcal{L}', 'loss'],
      ['∇L', '\\nabla \\mathcal{L}', 'loss gradient'],
      ['σ(z)', '\\sigma(z)', 'sigmoid'],
      ['softmax', '\\operatorname{softmax}', 'softmax'],
      ['ReLU', '\\operatorname{ReLU}', 'relu'],
      ['MSE', '\\operatorname{MSE}', 'mse'],
      ['KL', 'D_{\\mathrm{KL}}', 'kl divergence'],
      ['N(μ,Σ)', '\\mathcal{N}(\\mu,\\Sigma)', 'normal gaussian'],
    ]),
  },
]
