export const libraryPresets = [
  {
    id: 'circuitikz-sampler',
    group: 'Circuitikz',
    title: 'Circuitikz sampler',
    description: 'R, C, L, diode, transistor, op amp, ground',
    origin: { x: -9.4, y: 6.4 },
    stroke: '#111827',
    width: 5.8,
    height: 2.6,
    preview: 'circuit',
    packages: ['\\usepackage[american]{circuitikz}'],
    libraries: [],
    snippet: [
      '\\draw[draw=__COLOR__] (0,0) to[sV,l=$V_s$] (0,-2) -- (1.1,-2) to[R,l=$R$] (1.1,0) -- (0,0);',
      '\\draw[draw=__COLOR__] (1.35,0) to[C,l=$C$] (1.35,-2);',
      '\\draw[draw=__COLOR__] (2.2,0) to[L,l=$L$] (2.2,-2);',
      '\\draw[draw=__COLOR__] (3.0,0) to[D*,l=$D$] (3.0,-2) node[ground]{};',
      '\\node[npn, draw=__COLOR__] (q1) at (4.25,-1) {};',
      '\\node[op amp, draw=__COLOR__, scale=0.75] (op) at (5.45,-1) {};',
      '\\node[font=\\scriptsize, text=__COLOR__] at (2.9,0.45) {analog + semiconductors};',
    ],
  },
  {
    id: 'logic-gates-iec',
    group: 'Circuits',
    title: 'Logic gates IEC',
    description: 'AND, OR, NOT and signal wiring',
    origin: { x: -2.5, y: 6.2 },
    stroke: '#2563eb',
    width: 4.7,
    height: 2.2,
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[and gate IEC, draw=__COLOR__, logic gate inputs=nn] (and) at (1,0) {};',
      '\\node[or gate IEC, draw=__COLOR__, logic gate inputs=nn, right=1.3cm of and] (or) {};',
      '\\node[not gate IEC, draw=__COLOR__, right=1.3cm of or] (not) {};',
      '\\draw[draw=__COLOR__] (and.output) -- (or.input 1);',
      '\\draw[draw=__COLOR__] (or.output) -- (not.input);',
      '\\draw[draw=__COLOR__] (-0.35,0.3) -- (and.input 1);',
      '\\draw[draw=__COLOR__] (-0.35,-0.3) -- (and.input 2);',
      '\\node[font=\\scriptsize, text=__COLOR__] at (2.35,-1.0) {IEC logic circuit};',
    ],
  },
  {
    id: 'tikz-ee-iec',
    group: 'Circuits',
    title: 'TikZ EE IEC',
    description: 'Native TikZ electrical symbols',
    origin: { x: 3.2, y: 6.1 },
    stroke: '#64748b',
    width: 4.8,
    height: 2.2,
    preview: 'circuit',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.ee.IEC'],
    snippet: [
      '\\draw[draw=__COLOR__] (0,0) to [resistor={info=$R_1$}] (2,0) to [capacitor={info=$C$}] (4,0);',
      '\\draw[draw=__COLOR__] (0,-1) to [inductor={info=$L$}] (2,-1) to [diode={info=$D$}] (4,-1);',
      '\\node[font=\\scriptsize, text=__COLOR__] at (2,-1.65) {TikZ circuits.ee.IEC};',
    ],
  },
  {
    id: 'pgfplots-axis',
    group: 'PGFPlots',
    title: 'Axis plot',
    description: 'Functions, marks, legend, grid',
    origin: { x: -9.4, y: 2.4 },
    stroke: '#2563eb',
    width: 4.8,
    height: 3.2,
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    libraries: [],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[width=4.6cm,height=3cm,grid=both,axis lines=middle,legend style={font=\\scriptsize}]',
      '  \\addplot[__COLOR__, thick, domain=-2:2, samples=80] {x^2};',
      '  \\addplot[red!70!black, dashed, domain=-2:2, samples=80] {2-x^2};',
      '  \\legend{$x^2$,$2-x^2$}',
      '\\end{axis}',
    ],
  },
  {
    id: 'pgfplots-polar',
    group: 'PGFPlots',
    title: 'Polar plot',
    description: 'Parametric and polar curves',
    origin: { x: -3.7, y: 2.4 },
    stroke: '#dc2626',
    width: 4.2,
    height: 3.2,
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    libraries: [],
    pgfplotsLibraries: ['polar'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{polaraxis}[width=4cm,height=3cm,grid=both,xtick={0,45,...,315}]',
      '  \\addplot[__COLOR__, thick, domain=0:360, samples=180] {1+0.45*cos(3*x)};',
      '\\end{polaraxis}',
    ],
  },
  {
    id: 'pgfgantt-native',
    group: 'Planning',
    title: 'pgfgantt native',
    description: 'Standalone ganttchart environment',
    origin: { x: 1.7, y: 2.8 },
    stroke: '#059669',
    width: 6.6,
    height: 2.8,
    preview: 'gantt',
    packages: ['\\usepackage{pgfgantt}'],
    libraries: [],
    standalone: true,
    snippet: [
      '\\begin{ganttchart}[hgrid,vgrid,title height=1,bar height=.55]{1}{7}',
      '  \\gantttitle{ML Delivery}{7} \\\\',
      '  \\ganttbar{Data}{1}{2} \\\\',
      '  \\ganttbar{Features}{2}{4} \\\\',
      '  \\ganttbar{Training}{4}{6} \\\\',
      '  \\ganttbar{Evaluation}{6}{7}',
      '\\end{ganttchart}',
    ],
  },
  {
    id: 'tikz-cd-native',
    group: 'Math',
    title: 'tikz-cd diagram',
    description: 'Commutative diagram environment',
    origin: { x: -9.4, y: -1.5 },
    stroke: '#7c3aed',
    width: 4.6,
    height: 2.4,
    preview: 'matrix',
    packages: ['\\usepackage{tikz-cd}'],
    libraries: [],
    standalone: true,
    snippet: [
      '\\begin{tikzcd}',
      '  A \\arrow[r, "f"] \\arrow[d, "g" swap] & B \\arrow[d, "h"] \\\\',
      '  C \\arrow[r, "k" swap] & D',
      '\\end{tikzcd}',
    ],
  },
  {
    id: 'automata',
    group: 'Graph theory',
    title: 'Automata',
    description: 'Initial, accepting states and loops',
    origin: { x: -3.8, y: -1.2 },
    stroke: '#2563eb',
    width: 4.8,
    height: 2.4,
    preview: 'automata',
    packages: ['\\usepackage{tikz}'],
    libraries: ['automata', 'positioning', 'arrows.meta'],
    snippet: [
      '\\node[state, initial, draw=__COLOR__] (q0) at (0,0) {$q_0$};',
      '\\node[state, accepting, draw=__COLOR__, right=1.8cm of q0] (q1) {$q_1$};',
      '\\node[state, draw=__COLOR__, right=1.8cm of q1] (q2) {$q_2$};',
      '\\path[-{Stealth}, draw=__COLOR__] (q0) edge[bend left] node[above] {a} (q1) (q1) edge[loop above] node {b} () (q1) edge[bend left] node[below] {c} (q0) (q1) edge node[above] {d} (q2);',
    ],
  },
  {
    id: 'graphs',
    group: 'Graph theory',
    title: 'Graphs library',
    description: 'Graph syntax and layered edges',
    origin: { x: 2.0, y: -1.2 },
    stroke: '#0f766e',
    width: 4.8,
    height: 2.4,
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['graphs', 'arrows.meta'],
    snippet: [
      '\\graph[nodes={circle,draw=__COLOR__,inner sep=1.5pt}, edges={draw=__COLOR__,-{Stealth}}] {',
      '  a -> {b, c}; b -> d; c -> d; d -> e; c -> e;',
      '};',
    ],
  },
  {
    id: 'trees',
    group: 'Hierarchy',
    title: 'Tree',
    description: 'Recursive child syntax',
    origin: { x: -9.2, y: -4.7 },
    stroke: '#d97706',
    width: 4.6,
    height: 2.8,
    preview: 'tree',
    packages: ['\\usepackage{tikz}'],
    libraries: ['trees'],
    snippet: [
      '\\node[draw=__COLOR__, rounded corners=2pt] {Root}',
      '  child { node[draw=__COLOR__] {Left} child { node {A} } child { node {B} } }',
      '  child { node[draw=__COLOR__] {Right} child { node {C} } child { node {D} } };',
    ],
  },
  {
    id: 'mindmap',
    group: 'Hierarchy',
    title: 'Mindmap',
    description: 'Concept map with radial children',
    origin: { x: -3.6, y: -4.7 },
    stroke: '#0891b2',
    width: 4.8,
    height: 3.0,
    preview: 'mindmap',
    packages: ['\\usepackage{tikz}'],
    libraries: ['mindmap'],
    snippet: [
      '\\path[mindmap, concept color=cyan!55!black, text=white]',
      '  node[concept] {Model}',
      '    child[concept color=blue!55] { node[concept] {Data} }',
      '    child[concept color=teal!65] { node[concept] {Train} }',
      '    child[concept color=orange!80!black] { node[concept] {Deploy} };',
    ],
  },
  {
    id: 'matrix-of-nodes',
    group: 'Layout',
    title: 'Matrix',
    description: 'Matrix of nodes and arrows',
    origin: { x: 2.0, y: -4.5 },
    stroke: '#7c3aed',
    width: 4.8,
    height: 2.8,
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['matrix', 'arrows.meta'],
    snippet: [
      '\\matrix[matrix of nodes,nodes={draw=__COLOR__,minimum width=0.75cm,minimum height=0.45cm},column sep=0.45cm,row sep=0.35cm] (m) {',
      '  A & B & C \\\\',
      '  D & E & F \\\\',
      '};',
      '\\draw[-{Stealth}, draw=__COLOR__] (m-1-1) -- (m-2-2) -- (m-1-3);',
    ],
  },
  {
    id: 'positioning-fit',
    group: 'Layout',
    title: 'Positioning + fit',
    description: 'Node layout and grouped regions',
    origin: { x: -9.2, y: -7.1 },
    stroke: '#2563eb',
    width: 5.4,
    height: 2.2,
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['positioning', 'fit', 'backgrounds'],
    snippet: [
      '\\node[draw=__COLOR__, rounded corners=2pt] (a) at (0,0) {Input};',
      '\\node[draw=__COLOR__, rounded corners=2pt, right=0.7cm of a] (b) {Encoder};',
      '\\node[draw=__COLOR__, rounded corners=2pt, right=0.7cm of b] (c) {Head};',
      '\\draw[->, draw=__COLOR__] (a) -- (b) -- (c);',
      '\\begin{scope}[on background layer]',
      '  \\node[fill=__COLOR__!8, rounded corners=4pt, fit=(a)(b)(c), inner sep=6pt] {};',
      '\\end{scope}',
    ],
  },
  {
    id: 'calc-intersections',
    group: 'Geometry',
    title: 'Calc + intersections',
    description: 'Named paths and constructed points',
    origin: { x: -2.8, y: -7.1 },
    stroke: '#dc2626',
    width: 4.8,
    height: 2.2,
    preview: 'geometry',
    packages: ['\\usepackage{tikz}'],
    libraries: ['calc', 'intersections'],
    snippet: [
      '\\path[name path=lineA] (0,0) -- (3.2,1.6);',
      '\\path[name path=lineB] (0,1.5) -- (3.3,-0.2);',
      '\\draw[draw=__COLOR__] (0,0) -- (3.2,1.6) (0,1.5) -- (3.3,-0.2);',
      '\\path[name intersections={of=lineA and lineB, by=p}];',
      '\\fill[__COLOR__] (p) circle (2pt) node[above] {$p$};',
      '\\draw[draw=__COLOR__!55] ($(p)+(-.5,-.5)$) rectangle ($(p)+(.5,.5)$);',
    ],
  },
  {
    id: 'angles-quotes',
    group: 'Geometry',
    title: 'Angles + quotes',
    description: 'Annotated angle marks',
    origin: { x: 3.0, y: -7.1 },
    stroke: '#059669',
    width: 4.4,
    height: 2.2,
    preview: 'geometry',
    packages: ['\\usepackage{tikz}'],
    libraries: ['angles', 'quotes'],
    snippet: [
      '\\coordinate (A) at (0,0); \\coordinate (B) at (2.5,0); \\coordinate (C) at (1.1,1.4);',
      '\\draw[draw=__COLOR__] (A) -- (B) -- (C) -- cycle;',
      '\\pic[draw=__COLOR__, "$\\theta$", angle eccentricity=1.35, angle radius=0.55cm] {angle=A--B--C};',
    ],
  },
  {
    id: 'shapes-palette',
    group: 'Shapes',
    title: 'Shapes palette',
    description: 'Geometric, callout and multipart shapes',
    origin: { x: -9.2, y: 9.2 },
    stroke: '#d97706',
    width: 5.2,
    height: 2.4,
    preview: 'shapes',
    packages: ['\\usepackage{tikz}'],
    libraries: ['shapes.geometric', 'shapes.symbols', 'shapes.multipart', 'positioning'],
    snippet: [
      '\\node[draw=__COLOR__, diamond, aspect=2] at (0,0) {Decision};',
      '\\node[draw=__COLOR__, cloud, cloud puffs=8, right=1.7cm] at (0,0) {Cloud};',
      '\\node[draw=__COLOR__, rectangle split, rectangle split parts=3, right=3.8cm] at (0,0) {Head\\nodepart{second}Body\\nodepart{third}Tail};',
    ],
  },
  {
    id: 'decorations',
    group: 'Decorations',
    title: 'Decorations',
    description: 'Snakes, braces and markings',
    origin: { x: -3.0, y: 9.2 },
    stroke: '#7c3aed',
    width: 5.0,
    height: 2.4,
    preview: 'decorations',
    packages: ['\\usepackage{tikz}'],
    libraries: ['decorations.pathmorphing', 'decorations.pathreplacing', 'decorations.markings', 'arrows.meta', 'positioning'],
    snippet: [
      '\\draw[draw=__COLOR__, decorate, decoration={snake, amplitude=1.2mm, segment length=4mm}] (0,0) -- (4,0);',
      '\\draw[draw=__COLOR__, decorate, decoration={brace, amplitude=5pt}] (0,-0.7) -- (4,-0.7) node[midway, below=6pt] {span};',
      '\\draw[draw=__COLOR__, postaction={decorate}, decoration={markings, mark=at position .55 with {\\arrow{Stealth}}}] (0,-1.35) -- (4,-1.35);',
    ],
  },
  {
    id: 'patterns-fadings-shadows',
    group: 'Fills',
    title: 'Patterns + fadings',
    description: 'Pattern fills, shadows and soft fades',
    origin: { x: 3.0, y: 9.2 },
    stroke: '#0f766e',
    width: 4.8,
    height: 2.4,
    preview: 'fills',
    packages: ['\\usepackage{tikz}'],
    libraries: ['patterns', 'fadings', 'shadows'],
    snippet: [
      '\\filldraw[pattern=north east lines, pattern color=__COLOR__, draw=__COLOR__] (0,0) rectangle (1.2,1.2);',
      '\\node[draw=__COLOR__, fill=__COLOR__!12, drop shadow, rounded corners=3pt] at (2.4,0.6) {shadow};',
      '\\shade[inner color=__COLOR__!35, outer color=white] (4,0.6) circle (0.62);',
    ],
  },
  {
    id: 'background-layers',
    group: 'Layers',
    title: 'Background layer',
    description: 'Backgrounds and scoped highlights',
    origin: { x: -9.2, y: 12.1 },
    stroke: '#2563eb',
    width: 5.2,
    height: 2.3,
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['backgrounds', 'fit', 'positioning'],
    snippet: [
      '\\node[draw=__COLOR__] (a) at (0,0) {A};',
      '\\node[draw=__COLOR__, right=0.9cm of a] (b) {B};',
      '\\node[draw=__COLOR__, right=0.9cm of b] (c) {C};',
      '\\draw[->, draw=__COLOR__] (a) -- (b) -- (c);',
      '\\begin{scope}[on background layer]',
      '  \\node[fill=__COLOR__!10, rounded corners=6pt, fit=(a)(c), inner sep=8pt] {};',
      '\\end{scope}',
    ],
  },
  {
    id: 'spy-library',
    group: 'Inspection',
    title: 'Spy inset',
    description: 'Magnified detail callout',
    origin: { x: -3.0, y: 12.1 },
    stroke: '#dc2626',
    width: 4.8,
    height: 2.3,
    preview: 'spy',
    packages: ['\\usepackage{tikz}'],
    libraries: ['spy'],
    snippet: [
      '\\begin{scope}[spy using outlines={circle, magnification=2.4, size=1.25cm, connect spies}]',
      '  \\draw[draw=__COLOR__] plot[smooth] coordinates {(0,0) (.6,.8) (1.2,.25) (1.8,1.05) (2.5,.45)};',
      '  \\spy[__COLOR__] on (1.2,.25) in node at (3.35,.75);',
      '\\end{scope}',
    ],
  },
  {
    id: 'three-d',
    group: '3D',
    title: '3D coordinates',
    description: 'xyz canvas and cube projection',
    origin: { x: 2.8, y: 12.1 },
    stroke: '#64748b',
    width: 4.8,
    height: 2.4,
    preview: 'cube',
    packages: ['\\usepackage{tikz}'],
    libraries: ['3d', 'arrows.meta'],
    snippet: [
      '\\draw[-{Stealth}, draw=__COLOR__] (0,0,0) -- (2,0,0) node[right] {$x$};',
      '\\draw[-{Stealth}, draw=__COLOR__] (0,0,0) -- (0,1.6,0) node[above] {$y$};',
      '\\draw[-{Stealth}, draw=__COLOR__] (0,0,0) -- (0,0,1.6) node[left] {$z$};',
      '\\draw[draw=__COLOR__!70] (0,0,0) -- (1,0,0) -- (1,1,0) -- (0,1,0) -- cycle;',
      '\\draw[draw=__COLOR__!70] (0,0,1) -- (1,0,1) -- (1,1,1) -- (0,1,1) -- cycle;',
      '\\draw[draw=__COLOR__!70] (0,0,0) -- (0,0,1) (1,0,0) -- (1,0,1) (1,1,0) -- (1,1,1) (0,1,0) -- (0,1,1);',
    ],
  },
  {
    id: 'petri-net',
    group: 'Systems',
    title: 'Petri net',
    description: 'Places, transitions and tokens',
    origin: { x: -9.2, y: 15.0 },
    stroke: '#d97706',
    width: 4.6,
    height: 2.3,
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['petri', 'arrows.meta', 'positioning'],
    snippet: [
      '\\node[place, tokens=1, draw=__COLOR__] (p1) at (0,0) {};',
      '\\node[transition, draw=__COLOR__, right=1.3cm of p1] (t1) {};',
      '\\node[place, tokens=2, draw=__COLOR__, right=1.3cm of t1] (p2) {};',
      '\\draw[-{Stealth}, draw=__COLOR__] (p1) -- (t1) -- (p2);',
    ],
  },
  {
    id: 'er-diagram',
    group: 'Systems',
    title: 'ER diagram',
    description: 'Entity relationship notation',
    origin: { x: -3.5, y: 15.0 },
    stroke: '#0891b2',
    width: 5.0,
    height: 2.3,
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['er', 'positioning'],
    snippet: [
      '\\node[entity, draw=__COLOR__] (user) at (0,0) {User};',
      '\\node[relationship, draw=__COLOR__, right=1.5cm of user] (owns) {owns};',
      '\\node[entity, draw=__COLOR__, right=1.5cm of owns] (model) {Model};',
      '\\draw[draw=__COLOR__] (user) -- (owns) -- (model);',
    ],
  },
  {
    id: 'data-flow',
    group: 'ML/DL',
    title: 'ML DAG',
    description: 'Bayesian/dataflow graph',
    origin: { x: 2.3, y: 15.0 },
    stroke: '#2563eb',
    width: 5.1,
    height: 2.4,
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning', 'shapes.geometric'],
    snippet: [
      '\\node[circle, draw=__COLOR__] (x) at (0,0) {$x$};',
      '\\node[circle, draw=__COLOR__, right=1.2cm of x] (z) {$z$};',
      '\\node[circle, draw=__COLOR__, above right=.7cm and 1.2cm of z] (y) {$y$};',
      '\\node[circle, draw=__COLOR__, below right=.7cm and 1.2cm of z] (l) {$\\ell$};',
      '\\draw[-{Stealth}, draw=__COLOR__] (x) -- (z) -- (y);',
      '\\draw[-{Stealth}, draw=__COLOR__] (z) -- (l);',
      '\\draw[draw=__COLOR__!35, rounded corners] (-.35,-.45) rectangle (4.1,.95) node[below left] {plate};',
    ],
  },
]
