export const libraryPaletteItems = [
  {
    id: 'circuit-resistor',
    group: 'Circuit',
    title: 'Resistor',
    description: 'Two-terminal resistor',
    origin: { x: -2, y: 1 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'resistor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (2.2,0);'],
  },
  {
    id: 'circuit-capacitor',
    group: 'Circuit',
    title: 'Capacitor',
    description: 'Two-terminal capacitor',
    origin: { x: -2, y: 0 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'capacitor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[C,l=$C$] (2.2,0);'],
  },
  {
    id: 'circuit-inductor',
    group: 'Circuit',
    title: 'Inductor',
    description: 'Two-terminal inductor',
    origin: { x: -2, y: -1 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'inductor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[L,l=$L$] (2.2,0);'],
  },
  {
    id: 'circuit-diode',
    group: 'Circuit',
    title: 'Diode',
    description: 'Diode symbol',
    origin: { x: -2, y: -2 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'diode',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[D,l=$D$] (2.2,0);'],
  },
  {
    id: 'circuit-source-ground',
    group: 'Circuit',
    title: 'Source + ground',
    description: 'Voltage source reference',
    origin: { x: -2, y: -3 },
    width: 2.2,
    height: 1.7,
    stroke: '#111111',
    preview: 'source',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[V,l=$V_{in}$] (0,-1.2) node[ground] {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (1.5,0);',
    ],
  },
  {
    id: 'circuit-opamp',
    group: 'Circuit',
    title: 'Op amp',
    description: 'Operational amplifier',
    origin: { x: -1.5, y: 2 },
    width: 3.2,
    height: 2.2,
    stroke: '#111111',
    preview: 'opamp',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: [
      '\\node[op amp, draw=__COLOR__, line width=0.65pt] (op) at (1.4,-0.8) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) -- ++(-0.8,0) node[left] {$v_-$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.+) -- ++(-0.8,0) node[left] {$v_+$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.out) -- ++(0.8,0) node[right] {$v_o$};',
    ],
  },
  {
    id: 'logic-and-gate',
    group: 'Logic',
    title: 'AND gate',
    description: 'IEC logic gate',
    origin: { x: -1.5, y: 1.5 },
    width: 2.6,
    height: 1.8,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[and gate IEC, draw=__COLOR__, logic gate inputs=nn, line width=0.65pt] (and1) at (1,-0.6) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.input 1) -- ++(-0.7,0) node[left] {$a$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.input 2) -- ++(-0.7,0) node[left] {$b$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.output) -- ++(0.7,0) node[right] {$y$};',
    ],
  },
  {
    id: 'logic-not-gate',
    group: 'Logic',
    title: 'NOT gate',
    description: 'Inverter gate',
    origin: { x: -1.5, y: 0.2 },
    width: 2.4,
    height: 1.4,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[not gate IEC, draw=__COLOR__, line width=0.65pt] (not1) at (1,-0.5) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (not1.input) -- ++(-0.7,0) node[left] {$x$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (not1.output) -- ++(0.7,0) node[right] {$\\bar{x}$};',
    ],
  },
  {
    id: 'plot-axis',
    group: 'Plots',
    title: 'Axis plot',
    description: 'Publication axis',
    origin: { x: -2, y: 2 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[',
      '  width=5.2cm, height=3.2cm,',
      '  axis lines=left,',
      '  xlabel={$x$}, ylabel={$f(x)$},',
      '  tick style={draw=__COLOR__},',
      '  label style={font=\\small},',
      '  tick label style={font=\\scriptsize},',
      '  every axis plot/.append style={draw=__COLOR__, line width=0.65pt}',
      ']',
      '  \\addplot[smooth] coordinates {(-2,0.2) (-1,0.7) (0,1.0) (1,0.7) (2,0.2)};',
      '\\end{axis}',
    ],
  },
  {
    id: 'plot-error-bars',
    group: 'Plots',
    title: 'Error bars',
    description: 'Data with uncertainty',
    origin: { x: -2, y: -1.5 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[',
      '  width=5.2cm, height=3.2cm,',
      '  axis lines=left,',
      '  xlabel={$n$}, ylabel={Score},',
      '  error bars/y dir=both, error bars/y explicit,',
      '  tick label style={font=\\scriptsize}',
      ']',
      '  \\addplot+[only marks, mark=*, draw=__COLOR__, mark options={fill=white}, error bars/.cd, y explicit]',
      '    coordinates {(1,0.42) +- (0,0.05) (2,0.56) +- (0,0.04) (3,0.63) +- (0,0.06)};',
      '\\end{axis}',
    ],
  },
  {
    id: 'automata-state',
    group: 'Automata',
    title: 'State transition',
    description: 'Two states and arrow',
    origin: { x: -1.5, y: 1.2 },
    width: 3.8,
    height: 1.7,
    stroke: '#111111',
    preview: 'automata',
    packages: ['\\usepackage{tikz}'],
    libraries: ['automata', 'positioning', 'arrows.meta'],
    snippet: [
      '\\node[state, draw=__COLOR__, line width=0.65pt] (q0) at (0,0) {$q_0$};',
      '\\node[state, draw=__COLOR__, line width=0.65pt, right=1.6cm of q0] (q1) {$q_1$};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.65pt] (q0) -- node[above] {$a$} (q1);',
    ],
  },
  {
    id: 'matrix-block',
    group: 'Math',
    title: 'Matrix block',
    description: 'Matrix of nodes',
    origin: { x: -1.4, y: 1.4 },
    width: 3.2,
    height: 2.1,
    stroke: '#111111',
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['matrix'],
    snippet: [
      '\\matrix[matrix of math nodes, left delimiter={[}, right delimiter={]}, draw=__COLOR__, inner sep=3pt] (m) at (1,-0.7) {',
      '  a_{11} & a_{12} \\\\',
      '  a_{21} & a_{22} \\\\',
      '};',
    ],
  },
  {
    id: 'commutative-square',
    group: 'Math',
    title: 'Commutative square',
    description: 'Four objects and arrows',
    origin: { x: -1.8, y: 1.8 },
    width: 3.8,
    height: 2.8,
    stroke: '#111111',
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning'],
    snippet: [
      '\\node (A) at (0,0) {$A$};',
      '\\node[right=1.8cm of A] (B) {$B$};',
      '\\node[below=1.2cm of A] (C) {$C$};',
      '\\node[right=1.8cm of C] (D) {$D$};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (A) -- node[above] {$f$} (B);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (A) -- node[left] {$g$} (C);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (B) -- node[right] {$h$} (D);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (C) -- node[below] {$k$} (D);',
    ],
  },
  {
    id: 'dl-layer',
    group: 'ML / DL',
    title: 'Dense layer',
    description: 'Neural network layer pair',
    origin: { x: -1.5, y: 1.8 },
    width: 3.6,
    height: 3.4,
    stroke: '#111111',
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['positioning'],
    snippet: [
      '\\foreach \\i in {1,...,4} \\node[circle, draw=__COLOR__, minimum size=4.5mm, inner sep=0pt] (x\\i) at (0,-0.5*\\i) {};',
      '\\foreach \\j in {1,...,3} \\node[circle, draw=__COLOR__, minimum size=4.5mm, inner sep=0pt] (h\\j) at (1.6,-0.35-0.65*\\j) {};',
      '\\foreach \\i in {1,...,4} \\foreach \\j in {1,...,3} \\draw[draw=__COLOR__!45, line width=0.35pt] (x\\i) -- (h\\j);',
      '\\node[below=0.15cm of x4] {input};',
      '\\node[below=0.15cm of h3] {hidden};',
    ],
  },
  {
    id: 'ml-pipeline',
    group: 'ML / DL',
    title: 'Pipeline',
    description: 'Data to evaluation flow',
    origin: { x: -2.5, y: 0.8 },
    width: 5.8,
    height: 1.4,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning'],
    snippet: [
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm] (data) at (0,0) {data};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of data] (feat) {features};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of feat] (model) {model};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of model] (eval) {eval};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (data) -- (feat);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (feat) -- (model);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (model) -- (eval);',
    ],
  },
  {
    id: 'gantt-paper',
    group: 'Planning',
    title: 'Gantt bars',
    description: 'Compact project timeline',
    origin: { x: -2.4, y: 1.4 },
    width: 5.6,
    height: 2.7,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.5pt] (0,0) rectangle (4.8,-1.8);',
      '\\foreach \\x in {1,2,3,4} \\draw[draw=__COLOR__!25, line width=0.3pt] (\\x,0) -- (\\x,-1.8);',
      '\\node[anchor=east] at (-0.15,-0.35) {prep};',
      '\\node[anchor=east] at (-0.15,-0.9) {train};',
      '\\node[anchor=east] at (-0.15,-1.45) {write};',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (0.25,-0.52) rectangle (1.45,-0.18);',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (1.25,-1.07) rectangle (3.65,-0.73);',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (3.1,-1.62) rectangle (4.55,-1.28);',
    ],
  },
  {
    id: 'tree-small',
    group: 'Graph',
    title: 'Tree',
    description: 'Root with children',
    origin: { x: -1.5, y: 1.5 },
    width: 3.2,
    height: 2.5,
    stroke: '#111111',
    preview: 'tree',
    packages: ['\\usepackage{tikz}'],
    libraries: ['trees'],
    snippet: [
      '\\node[draw=__COLOR__, circle, inner sep=1.5pt] {root}',
      '  child { node[draw=__COLOR__, circle, inner sep=1.5pt] {a} }',
      '  child { node[draw=__COLOR__, circle, inner sep=1.5pt] {b} };',
    ],
  },
  {
    id: 'angle-marker',
    group: 'Geometry',
    title: 'Angle marker',
    description: 'Annotated angle',
    origin: { x: -1.2, y: 0.8 },
    width: 2.8,
    height: 1.8,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['angles', 'quotes'],
    snippet: [
      '\\coordinate (A) at (0,0);',
      '\\coordinate (B) at (1.8,0);',
      '\\coordinate (C) at (1.2,1.0);',
      '\\draw[draw=__COLOR__, line width=0.65pt] (A) -- (B) -- (C);',
      '\\pic[draw=__COLOR__, "$\\theta$", angle radius=0.45cm] {angle=A--B--C};',
    ],
  },
  {
    id: 'brace-annotation',
    group: 'Annotation',
    title: 'Brace label',
    description: 'Brace annotation',
    origin: { x: -1.4, y: 0.8 },
    width: 3.2,
    height: 1.5,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['decorations.pathreplacing'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (2.4,0);',
      '\\draw[decorate, decoration={brace, amplitude=4pt}, draw=__COLOR__, line width=0.55pt] (0,0.25) -- node[above=5pt] {$n$ samples} (2.4,0.25);',
    ],
  },
]
