export const libraryPaletteItems = [
  {
    id: 'circuit-resistor',
    group: 'Circuit',
    title: 'Resistor',
    description: 'Two-terminal resistor',
    origin: { x: -2, y: 1 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'resistor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (2.2,0);'],
  },
  {
    id: 'circuit-capacitor',
    group: 'Circuit',
    title: 'Capacitor',
    description: 'Two-terminal capacitor',
    origin: { x: -2, y: 0 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'capacitor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[C,l=$C$] (2.2,0);'],
  },
  {
    id: 'circuit-inductor',
    group: 'Circuit',
    title: 'Inductor',
    description: 'Two-terminal inductor',
    origin: { x: -2, y: -1 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'inductor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[L,l=$L$] (2.2,0);'],
  },
  {
    id: 'circuit-diode',
    group: 'Circuit',
    title: 'Diode',
    description: 'Diode symbol',
    origin: { x: -2, y: -2 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'diode',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[D,l=$D$] (2.2,0);'],
  },
  {
    id: 'circuit-source-ground',
    group: 'Circuit',
    title: 'Source + ground',
    description: 'Voltage source reference',
    origin: { x: -2, y: -3 },
    width: 2.2,
    height: 1.7,
    stroke: '#111111',
    preview: 'source',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[V,l=$V_{in}$] (0,-1.2) node[ground] {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (1.5,0);',
    ],
  },
  {
    id: 'circuit-opamp',
    group: 'Circuit',
    title: 'Op amp',
    description: 'Operational amplifier',
    origin: { x: -1.5, y: 2 },
    width: 3.2,
    height: 2.2,
    stroke: '#111111',
    preview: 'opamp',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: [
      '\\node[op amp, draw=__COLOR__, line width=0.65pt] (op) at (1.4,-0.8) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) -- ++(-0.8,0) node[left] {$v_-$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.+) -- ++(-0.8,0) node[left] {$v_+$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.out) -- ++(0.8,0) node[right] {$v_o$};',
    ],
  },
  {
    id: 'logic-and-gate',
    group: 'Logic',
    title: 'AND gate',
    description: 'IEC logic gate',
    origin: { x: -1.5, y: 1.5 },
    width: 2.6,
    height: 1.8,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[and gate IEC, draw=__COLOR__, logic gate inputs=nn, line width=0.65pt] (and1) at (1,-0.6) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.input 1) -- ++(-0.7,0) node[left] {$a$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.input 2) -- ++(-0.7,0) node[left] {$b$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.output) -- ++(0.7,0) node[right] {$y$};',
    ],
  },
  {
    id: 'logic-not-gate',
    group: 'Logic',
    title: 'NOT gate',
    description: 'Inverter gate',
    origin: { x: -1.5, y: 0.2 },
    width: 2.4,
    height: 1.4,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[not gate IEC, draw=__COLOR__, line width=0.65pt] (not1) at (1,-0.5) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (not1.input) -- ++(-0.7,0) node[left] {$x$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (not1.output) -- ++(0.7,0) node[right] {$\\bar{x}$};',
    ],
  },
  {
    id: 'plot-axis',
    group: 'Plots',
    title: 'Axis plot',
    description: 'Publication axis',
    origin: { x: -2, y: 2 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[',
      '  width=5.2cm, height=3.2cm,',
      '  axis lines=left,',
      '  xlabel={$x$}, ylabel={$f(x)$},',
      '  tick style={draw=__COLOR__},',
      '  label style={font=\\small},',
      '  tick label style={font=\\scriptsize},',
      '  every axis plot/.append style={draw=__COLOR__, line width=0.65pt}',
      ']',
      '  \\addplot[smooth] coordinates {(-2,0.2) (-1,0.7) (0,1.0) (1,0.7) (2,0.2)};',
      '\\end{axis}',
    ],
  },
  {
    id: 'plot-error-bars',
    group: 'Plots',
    title: 'Error bars',
    description: 'Data with uncertainty',
    origin: { x: -2, y: -1.5 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[',
      '  width=5.2cm, height=3.2cm,',
      '  axis lines=left,',
      '  xlabel={$n$}, ylabel={Score},',
      '  error bars/y dir=both, error bars/y explicit,',
      '  tick label style={font=\\scriptsize}',
      ']',
      '  \\addplot+[only marks, mark=*, draw=__COLOR__, mark options={fill=white}, error bars/.cd, y explicit]',
      '    coordinates {(1,0.42) +- (0,0.05) (2,0.56) +- (0,0.04) (3,0.63) +- (0,0.06)};',
      '\\end{axis}',
    ],
  },
  {
    id: 'automata-state',
    group: 'Automata',
    title: 'State transition',
    description: 'Two states and arrow',
    origin: { x: -1.5, y: 1.2 },
    width: 3.8,
    height: 1.7,
    stroke: '#111111',
    preview: 'automata',
    packages: ['\\usepackage{tikz}'],
    libraries: ['automata', 'positioning', 'arrows.meta'],
    snippet: [
      '\\node[state, draw=__COLOR__, line width=0.65pt] (q0) at (0,0) {$q_0$};',
      '\\node[state, draw=__COLOR__, line width=0.65pt, right=1.6cm of q0] (q1) {$q_1$};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.65pt] (q0) -- node[above] {$a$} (q1);',
    ],
  },
  {
    id: 'matrix-block',
    group: 'Math',
    title: 'Matrix block',
    description: 'Matrix of nodes',
    origin: { x: -1.4, y: 1.4 },
    width: 3.2,
    height: 2.1,
    stroke: '#111111',
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['matrix'],
    snippet: [
      '\\matrix[matrix of math nodes, left delimiter={[}, right delimiter={]}, draw=__COLOR__, inner sep=3pt] (m) at (1,-0.7) {',
      '  a_{11} & a_{12} \\\\',
      '  a_{21} & a_{22} \\\\',
      '};',
    ],
  },
  {
    id: 'commutative-square',
    group: 'Math',
    title: 'Commutative square',
    description: 'Four objects and arrows',
    origin: { x: -1.8, y: 1.8 },
    width: 3.8,
    height: 2.8,
    stroke: '#111111',
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning'],
    snippet: [
      '\\node (A) at (0,0) {$A$};',
      '\\node[right=1.8cm of A] (B) {$B$};',
      '\\node[below=1.2cm of A] (C) {$C$};',
      '\\node[right=1.8cm of C] (D) {$D$};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (A) -- node[above] {$f$} (B);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (A) -- node[left] {$g$} (C);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (B) -- node[right] {$h$} (D);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (C) -- node[below] {$k$} (D);',
    ],
  },
  {
    id: 'dl-layer',
    group: 'ML / DL',
    title: 'Dense layer',
    description: 'Neural network layer pair',
    origin: { x: -1.5, y: 1.8 },
    width: 3.6,
    height: 3.4,
    stroke: '#111111',
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['positioning'],
    snippet: [
      '\\foreach \\i in {1,...,4} \\node[circle, draw=__COLOR__, minimum size=4.5mm, inner sep=0pt] (x\\i) at (0,-0.5*\\i) {};',
      '\\foreach \\j in {1,...,3} \\node[circle, draw=__COLOR__, minimum size=4.5mm, inner sep=0pt] (h\\j) at (1.6,-0.35-0.65*\\j) {};',
      '\\foreach \\i in {1,...,4} \\foreach \\j in {1,...,3} \\draw[draw=__COLOR__!45, line width=0.35pt] (x\\i) -- (h\\j);',
      '\\node[below=0.15cm of x4] {input};',
      '\\node[below=0.15cm of h3] {hidden};',
    ],
  },
  {
    id: 'ml-pipeline',
    group: 'ML / DL',
    title: 'Pipeline',
    description: 'Data to evaluation flow',
    origin: { x: -2.5, y: 0.8 },
    width: 5.8,
    height: 1.4,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning'],
    snippet: [
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm] (data) at (0,0) {data};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of data] (feat) {features};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of feat] (model) {model};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of model] (eval) {eval};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (data) -- (feat);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (feat) -- (model);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (model) -- (eval);',
    ],
  },
  {
    id: 'gantt-paper',
    group: 'Planning',
    title: 'Gantt bars',
    description: 'Compact project timeline',
    origin: { x: -2.4, y: 1.4 },
    width: 5.6,
    height: 2.7,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.5pt] (0,0) rectangle (4.8,-1.8);',
      '\\foreach \\x in {1,2,3,4} \\draw[draw=__COLOR__!25, line width=0.3pt] (\\x,0) -- (\\x,-1.8);',
      '\\node[anchor=east] at (-0.15,-0.35) {prep};',
      '\\node[anchor=east] at (-0.15,-0.9) {train};',
      '\\node[anchor=east] at (-0.15,-1.45) {write};',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (0.25,-0.52) rectangle (1.45,-0.18);',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (1.25,-1.07) rectangle (3.65,-0.73);',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (3.1,-1.62) rectangle (4.55,-1.28);',
    ],
  },
  {
    id: 'tree-small',
    group: 'Graph',
    title: 'Tree',
    description: 'Root with children',
    origin: { x: -1.5, y: 1.5 },
    width: 3.2,
    height: 2.5,
    stroke: '#111111',
    preview: 'tree',
    packages: ['\\usepackage{tikz}'],
    libraries: ['trees'],
    snippet: [
      '\\node[draw=__COLOR__, circle, inner sep=1.5pt] {root}',
      '  child { node[draw=__COLOR__, circle, inner sep=1.5pt] {a} }',
      '  child { node[draw=__COLOR__, circle, inner sep=1.5pt] {b} };',
    ],
  },
  {
    id: 'angle-marker',
    group: 'Geometry',
    title: 'Angle marker',
    description: 'Annotated angle',
    origin: { x: -1.2, y: 0.8 },
    width: 2.8,
    height: 1.8,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['angles', 'quotes'],
    snippet: [
      '\\coordinate (A) at (0,0);',
      '\\coordinate (B) at (1.8,0);',
      '\\coordinate (C) at (1.2,1.0);',
      '\\draw[draw=__COLOR__, line width=0.65pt] (A) -- (B) -- (C);',
      '\\pic[draw=__COLOR__, "$\\theta$", angle radius=0.45cm] {angle=A--B--C};',
    ],
  },
  {
    id: 'brace-annotation',
    group: 'Annotation',
    title: 'Brace label',
    description: 'Brace annotation',
    origin: { x: -1.4, y: 0.8 },
    width: 3.2,
    height: 1.5,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['decorations.pathreplacing'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (2.4,0);',
      '\\draw[decorate, decoration={brace, amplitude=4pt}, draw=__COLOR__, line width=0.55pt] (0,0.25) -- node[above=5pt] {$n$ samples} (2.4,0.25);',
    ],
  },
  ...[
    ['circuit-battery', 'Circuit', 'Battery', 'DC source', 'source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[battery1,l=$V$] (2.0,0);']],
    ['circuit-current-source', 'Circuit', 'Current source', 'Independent current source', 'source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[I,l=$I$] (2.0,0);']],
    ['circuit-switch', 'Circuit', 'Switch', 'Open switch', 'switch', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[normal open switch,l=$S$] (2.0,0);']],
    ['circuit-lamp', 'Circuit', 'Lamp', 'Lamp load', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[lamp,l=$L$] (2.0,0);']],
    ['circuit-led', 'Circuit', 'LED', 'Light emitting diode', 'diode', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[led,l=$D$] (2.0,0);']],
    ['circuit-zener', 'Circuit', 'Zener diode', 'Zener regulator diode', 'diode', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[zD,l=$D_z$] (2.0,0);']],
    ['circuit-npn', 'Circuit', 'NPN transistor', 'BJT transistor', 'npn', ['\\node[npn, draw=__COLOR__, line width=0.65pt] (q) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.B) -- ++(-0.6,0) node[left] {$B$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.C) -- ++(0,0.55) node[above] {$C$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.E) -- ++(0,-0.55) node[below] {$E$};']],
    ['circuit-pnp', 'Circuit', 'PNP transistor', 'BJT transistor', 'pnp', ['\\node[pnp, draw=__COLOR__, line width=0.65pt] (q) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.B) -- ++(-0.6,0) node[left] {$B$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.C) -- ++(0,0.55) node[above] {$C$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.E) -- ++(0,-0.55) node[below] {$E$};']],
    ['circuit-nmos', 'Circuit', 'NMOS', 'MOS transistor', 'nmos', ['\\node[nmos, draw=__COLOR__, line width=0.65pt] (m) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.G) -- ++(-0.6,0) node[left] {$G$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.D) -- ++(0,0.55) node[above] {$D$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.S) -- ++(0,-0.55) node[below] {$S$};']],
    ['circuit-pmos', 'Circuit', 'PMOS', 'MOS transistor', 'pmos', ['\\node[pmos, draw=__COLOR__, line width=0.65pt] (m) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.G) -- ++(-0.6,0) node[left] {$G$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.D) -- ++(0,0.55) node[above] {$D$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.S) -- ++(0,-0.55) node[below] {$S$};']],
    ['circuit-rl-lowpass', 'Circuit', 'RL branch', 'Resistor and inductor', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (1.6,0) to[L,l=$L$] (3.2,0);']],
    ['circuit-rc-lowpass', 'Circuit', 'RC low-pass', 'Filter topology', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (2,0) -- (3,0);', '\\draw[draw=__COLOR__, line width=0.65pt] (2,0) to[C,l=$C$] (2,-1.3) node[ground] {};']],
  ].map(([id, group, title, description, preview, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.4, y: 1 },
    width: 3.4,
    height: 1.9,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet,
  })),
  ...[
    ['logic-or-gate', 'OR gate', 'IEC logic gate', 'or gate IEC', 'nn'],
    ['logic-xor-gate', 'XOR gate', 'IEC logic gate', 'xor gate IEC', 'nn'],
    ['logic-nand-gate', 'NAND gate', 'IEC logic gate', 'nand gate IEC', 'nn'],
    ['logic-nor-gate', 'NOR gate', 'IEC logic gate', 'nor gate IEC', 'nn'],
    ['logic-xnor-gate', 'XNOR gate', 'IEC logic gate', 'xnor gate IEC', 'nn'],
  ].map(([id, title, description, gate, inputs]) => ({
    id,
    group: 'Logic',
    title,
    description,
    origin: { x: -1.5, y: 1.2 },
    width: 2.8,
    height: 1.7,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      `\\node[${gate}, draw=__COLOR__, logic gate inputs=${inputs}, line width=0.65pt] (g) at (1,-0.5) {};`,
      '\\draw[draw=__COLOR__, line width=0.65pt] (g.input 1) -- ++(-0.7,0) node[left] {$a$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (g.input 2) -- ++(-0.7,0) node[left] {$b$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (g.output) -- ++(0.7,0) node[right] {$y$};',
    ],
  })),
  ...[
    ['shape-process', 'Shapes', 'Process box', 'Rectangular process node', 'flow', ['positioning'], ['\\node[draw=__COLOR__, line width=0.6pt, minimum width=2.2cm, minimum height=0.65cm] (p) at (0,0) {process};']],
    ['shape-decision', 'Shapes', 'Decision diamond', 'Decision node', 'flow', ['shapes.geometric'], ['\\node[diamond, draw=__COLOR__, line width=0.6pt, aspect=2, inner sep=1pt] (d) at (0,0) {test};']],
    ['shape-ellipse-node', 'Shapes', 'Ellipse node', 'State or variable node', 'automata', ['shapes.geometric'], ['\\node[ellipse, draw=__COLOR__, line width=0.6pt, minimum width=1.8cm] (e) at (0,0) {$x$};']],
    ['shape-cylinder', 'Shapes', 'Cylinder', 'Database style node', 'flow', ['shapes.geometric'], ['\\node[cylinder, draw=__COLOR__, line width=0.6pt, shape border rotate=90, aspect=0.25, minimum height=1.1cm] (db) at (0,0) {data};']],
    ['shape-cloud', 'Shapes', 'Cloud', 'Cloud node', 'flow', ['shapes.symbols'], ['\\node[cloud, draw=__COLOR__, line width=0.6pt, cloud puffs=11, minimum width=2.1cm] (c) at (0,0) {cloud};']],
    ['shape-callout', 'Shapes', 'Callout', 'Annotation callout', 'flow', ['shapes.callouts'], ['\\node[rectangle callout, callout relative pointer={(0.8,-0.5)}, draw=__COLOR__, line width=0.6pt] (c) at (0,0) {note};']],
    ['shape-fit-box', 'Shapes', 'Fit box', 'Dashed grouping box', 'flow', ['fit', 'positioning'], ['\\node[draw=__COLOR__, dashed, line width=0.55pt, inner sep=6pt, fit={(0,0) (2,-1)}] (fitbox) {};']],
    ['shape-rounded-module', 'Shapes', 'Module', 'Rounded module box', 'flow', ['positioning'], ['\\node[draw=__COLOR__, rounded corners=2pt, line width=0.6pt, minimum width=2cm, minimum height=0.7cm] (m) at (0,0) {module};']],
    ['shape-table', 'Shapes', 'Small table', 'Tabular node mockup', 'matrix', ['matrix'], ['\\matrix[matrix of nodes, draw=__COLOR__, line width=0.55pt, nodes={minimum width=0.8cm, minimum height=0.35cm}] (t) at (0,0) { A & B \\\\ 1 & 2 \\\\ };']],
    ['shape-image-placeholder', 'Shapes', 'Image frame', 'Figure panel placeholder', 'flow', [], ['\\draw[draw=__COLOR__, line width=0.6pt] (0,0) rectangle (2.4,-1.4);', '\\draw[draw=__COLOR__!60, line width=0.4pt] (0,0) -- (2.4,-1.4) (0,-1.4) -- (2.4,0);']],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.2, y: 1 },
    width: 3,
    height: 2,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    ['plot-scatter', 'Scatter plot', 'Marks with trend', ['\\begin{axis}[width=5cm,height=3.2cm,axis lines=left,xlabel={$x$},ylabel={$y$},tick label style={font=\\scriptsize}]', '  \\addplot[only marks, mark=*, draw=__COLOR__] coordinates {(0,0.2) (1,0.7) (2,0.9) (3,1.6)};', '  \\addplot[draw=__COLOR__, line width=0.55pt] coordinates {(0,0.25) (3,1.45)};', '\\end{axis}']],
    ['plot-bar', 'Bar chart', 'Compact bars', ['\\begin{axis}[width=5cm,height=3.2cm,ybar,axis lines=left,symbolic x coords={A,B,C},xtick=data,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, fill=__COLOR__!15] coordinates {(A,2) (B,3.5) (C,2.8)};', '\\end{axis}']],
    ['plot-histogram', 'Histogram', 'Distribution bars', ['\\begin{axis}[width=5cm,height=3.2cm,ybar interval,axis lines=left,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, fill=__COLOR__!12] coordinates {(0,1) (1,4) (2,6) (3,3) (4,1)};', '\\end{axis}']],
    ['plot-heatmap', 'Heatmap', 'Matrix heatmap', ['\\begin{axis}[width=4.4cm,height=3.4cm,view={0}{90},colorbar,tick label style={font=\\scriptsize}]', '  \\addplot3[surf, shader=flat] coordinates {(0,0,0.1) (0,1,0.4) (1,0,0.7) (1,1,0.2)};', '\\end{axis}']],
    ['plot-boxplot', 'Box plot', 'Statistical summary', ['\\begin{axis}[width=4.8cm,height=3.2cm,boxplot/draw direction=y,axis lines=left,tick label style={font=\\scriptsize}]', '  \\addplot+[boxplot prepared={lower whisker=1, lower quartile=2, median=3, upper quartile=4, upper whisker=5}, draw=__COLOR__] coordinates {};', '\\end{axis}']],
    ['plot-semilog', 'Semilog axis', 'Logarithmic y axis', ['\\begin{semilogyaxis}[width=5cm,height=3.2cm,axis lines=left,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,1) (1,3) (2,10) (3,25)};', '\\end{semilogyaxis}']],
    ['plot-polar', 'Polar plot', 'Polar curve', ['\\begin{polaraxis}[width=4cm,height=4cm,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, samples=120, domain=0:360] {1+0.35*cos(3*x)};', '\\end{polaraxis}'], ['polar']],
    ['plot-group', 'Group plots', 'Two aligned panels', ['\\begin{groupplot}[group style={group size=2 by 1}, width=3.2cm, height=2.6cm]', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,0) (1,1)};', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,1) (1,0)};', '\\end{groupplot}'], ['groupplots']],
  ].map(([id, title, description, snippet, pgfplotsLibraries = []]) => ({
    id,
    group: 'Plots',
    title,
    description,
    origin: { x: -2, y: 2 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    pgfplotsLibraries,
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet,
  })),
  ...[
    ['graph-directed', 'Graph', 'Directed edge', 'Two nodes with edge', 'network', ['arrows.meta', 'positioning'], ['\\node[circle, draw=__COLOR__] (a) at (0,0) {$a$};', '\\node[circle, draw=__COLOR__, right=1.4cm of a] (b) {$b$};', '\\draw[-{Stealth}, draw=__COLOR__] (a) -- (b);']],
    ['graph-bipartite', 'Graph', 'Bipartite graph', 'Two node partitions', 'network', ['positioning'], ['\\foreach \\i in {1,2,3} \\node[circle, draw=__COLOR__, inner sep=1.5pt] (u\\i) at (0,-0.55*\\i) {};', '\\foreach \\j in {1,2} \\node[circle, draw=__COLOR__, inner sep=1.5pt] (v\\j) at (1.6,-0.75*\\j-0.2) {};', '\\foreach \\i in {1,2,3} \\foreach \\j in {1,2} \\draw[draw=__COLOR__!55] (u\\i) -- (v\\j);']],
    ['automata-loop', 'Automata', 'Self loop', 'State with loop', 'automata', ['automata', 'positioning', 'arrows.meta'], ['\\node[state, draw=__COLOR__] (q) at (0,0) {$q$};', '\\draw[-{Stealth}, draw=__COLOR__] (q) edge[loop above] node {$a$} (q);']],
    ['petri-basic', 'Petri', 'Petri net', 'Place transition place', 'network', ['petri', 'positioning', 'arrows.meta'], ['\\node[place, draw=__COLOR__] (p1) at (0,0) {};', '\\node[transition, draw=__COLOR__, right=1cm of p1] (t) {};', '\\node[place, draw=__COLOR__, right=1cm of t] (p2) {};', '\\draw[-{Stealth}, draw=__COLOR__] (p1) -- (t) -- (p2);']],
    ['flow-decision', 'Flow', 'Decision branch', 'Diamond branch flow', 'flow', ['arrows.meta', 'shapes.geometric', 'positioning'], ['\\node[diamond, draw=__COLOR__, aspect=2] (d) at (0,0) {ok?};', '\\node[draw=__COLOR__, below left=0.7cm and 0.7cm of d] (n) {no};', '\\node[draw=__COLOR__, below right=0.7cm and 0.7cm of d] (y) {yes};', '\\draw[-{Stealth}, draw=__COLOR__] (d) -- (n);', '\\draw[-{Stealth}, draw=__COLOR__] (d) -- (y);']],
    ['flow-swimlane', 'Flow', 'Swimlane', 'Two-lane process', 'flow', ['arrows.meta', 'positioning'], ['\\draw[draw=__COLOR__!45] (0,0) rectangle (4,-1.8);', '\\draw[draw=__COLOR__!25] (0,-0.9) -- (4,-0.9);', '\\node[draw=__COLOR__] (a) at (0.9,-0.45) {A};', '\\node[draw=__COLOR__] (b) at (3.1,-1.35) {B};', '\\draw[-{Stealth}, draw=__COLOR__] (a) -- (b);']],
    ['er-entity', 'ER', 'Entity relation', 'Entity with relationship', 'flow', ['er', 'positioning'], ['\\node[entity, draw=__COLOR__] (e1) at (0,0) {User};', '\\node[relationship, draw=__COLOR__, right=1.4cm of e1] (r) {owns};', '\\node[entity, draw=__COLOR__, right=1.4cm of r] (e2) {File};', '\\draw[draw=__COLOR__] (e1) -- (r) -- (e2);']],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.8, y: 1.3 },
    width: 4.8,
    height: 2.8,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    ['ml-confusion', 'ML / DL', 'Confusion matrix', '2x2 classifier matrix', 'matrix', ['matrix'], ['\\matrix[matrix of nodes, draw=__COLOR__, nodes={minimum width=0.9cm, minimum height=0.45cm}] (cm) at (0,0) { TP & FP \\\\ FN & TN \\\\ };']],
    ['ml-roc', 'ML / DL', 'ROC curve', 'Classifier ROC axis', 'plot', [], ['\\begin{axis}[width=4.5cm,height=3.2cm,axis lines=left,xlabel={FPR},ylabel={TPR},xmin=0,xmax=1,ymin=0,ymax=1]', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,0) (0.1,0.45) (0.35,0.75) (1,1)};', '  \\addplot[draw=__COLOR__!35, dashed] coordinates {(0,0) (1,1)};', '\\end{axis}'], ['\\usepackage{pgfplots}'], [], ['\\pgfplotsset{compat=1.18}']],
    ['ml-training-curve', 'ML / DL', 'Training curve', 'Loss versus epoch', 'plot', [], ['\\begin{axis}[width=4.8cm,height=3.2cm,axis lines=left,xlabel={epoch},ylabel={loss}]', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,1.2) (1,0.7) (2,0.45) (3,0.32)};', '\\end{axis}'], ['\\usepackage{pgfplots}'], [], ['\\pgfplotsset{compat=1.18}']],
    ['dl-cnn-stack', 'ML / DL', 'CNN stack', 'Convolutional feature blocks', 'cube', ['3d', 'positioning'], ['\\draw[draw=__COLOR__, fill=__COLOR__!5] (0,0) rectangle (0.55,1.2);', '\\draw[draw=__COLOR__, fill=__COLOR__!8] (0.75,0.15) rectangle (1.25,1.05);', '\\draw[draw=__COLOR__, fill=__COLOR__!12] (1.45,0.3) rectangle (1.85,0.9);', '\\node[below] at (0.9,-0.1) {conv};']],
    ['dl-transformer', 'ML / DL', 'Transformer block', 'Attention plus MLP', 'flow', ['arrows.meta', 'positioning'], ['\\node[draw=__COLOR__, minimum width=2cm] (attn) at (0,0) {attention};', '\\node[draw=__COLOR__, minimum width=2cm, below=0.55cm of attn] (mlp) {MLP};', '\\draw[-{Stealth}, draw=__COLOR__] (attn) -- (mlp);', '\\draw[draw=__COLOR__, rounded corners] (-1.25,0.35) rectangle (1.25,-1.0);']],
    ['dl-residual', 'ML / DL', 'Residual block', 'Skip connection', 'flow', ['arrows.meta', 'positioning'], ['\\node[draw=__COLOR__] (f) at (0,0) {$F(x)$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1.2,0) -- (f) -- (1.2,0);', '\\draw[-{Stealth}, draw=__COLOR__] (-1.0,0) |- (0,-0.75) -| (1.0,0);', '\\node[right] at (1.25,0) {$x+F(x)$};']],
    ['dl-autoencoder', 'ML / DL', 'Autoencoder', 'Encoder latent decoder', 'network', ['positioning'], ['\\node[draw=__COLOR__] (enc) at (0,0) {encoder};', '\\node[circle, draw=__COLOR__, right=0.7cm of enc] (z) {$z$};', '\\node[draw=__COLOR__, right=0.7cm of z] (dec) {decoder};', '\\draw[draw=__COLOR__] (enc) -- (z) -- (dec);']],
  ].map(([id, group, title, description, preview, libraries, snippet, packages = ['\\usepackage{tikz}'], pgfplotsLibraries = [], afterPreamble = []]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.8, y: 1.6 },
    width: 4.8,
    height: 3,
    stroke: '#111111',
    preview,
    packages,
    libraries,
    pgfplotsLibraries,
    afterPreamble,
    snippet,
  })),
  ...[
    ['geom-vector', 'Geometry', 'Vector', 'Arrowed vector', 'flow', ['arrows.meta'], ['\\draw[-{Stealth}, draw=__COLOR__, line width=0.65pt] (0,0) -- (2,1) node[right] {$\\mathbf{v}$};']],
    ['geom-basis', 'Geometry', 'Basis axes', 'Local coordinate frame', 'flow', ['arrows.meta'], ['\\draw[-{Stealth}, draw=__COLOR__] (0,0) -- (1.6,0) node[right] {$e_1$};', '\\draw[-{Stealth}, draw=__COLOR__] (0,0) -- (0,1.3) node[above] {$e_2$};']],
    ['geom-right-angle', 'Geometry', 'Right angle', 'Orthogonal marker', 'flow', [], ['\\draw[draw=__COLOR__] (0,0) -- (1.8,0) -- (1.8,1.1);', '\\draw[draw=__COLOR__] (1.55,0) -- (1.55,0.25) -- (1.8,0.25);']],
    ['annot-dimension', 'Annotation', 'Dimension line', 'Measured span', 'flow', ['arrows.meta'], ['\\draw[{Stealth}-{Stealth}, draw=__COLOR__, line width=0.55pt] (0,0) -- node[above] {$d$} (2.4,0);', '\\draw[draw=__COLOR__!65] (0,0.15) -- (0,-0.15) (2.4,0.15) -- (2.4,-0.15);']],
    ['annot-dashed-region', 'Annotation', 'Dashed region', 'Highlighted domain', 'flow', ['patterns'], ['\\draw[draw=__COLOR__, dashed, line width=0.55pt] (0,0) rectangle (2,-1.2);', '\\node at (1,-0.6) {$\\Omega$};']],
    ['annot-bracket', 'Annotation', 'Bracket label', 'Square bracket annotation', 'flow', ['decorations.pathreplacing'], ['\\draw[decorate, decoration={brace, mirror, amplitude=4pt}, draw=__COLOR__] (0,0) -- node[below=5pt] {window} (2.4,0);']],
    ['math-equation-node', 'Math', 'Equation node', 'Centered equation label', 'flow', [], ['\\node[draw=__COLOR__, inner sep=4pt] at (0,0) {$y = X\\beta + \\epsilon$};']],
    ['math-theorem-box', 'Math', 'Theorem box', 'Small framed statement', 'flow', [], ['\\node[draw=__COLOR__, align=left, inner sep=5pt] at (0,0) {Lemma.\\\\If $A$, then $B$.};']],
    ['math-comm-triangle', 'Math', 'Commutative triangle', 'Triangle diagram', 'network', ['arrows.meta', 'positioning'], ['\\node (A) at (0,0.9) {$A$};', '\\node (B) at (-0.9,-0.6) {$B$};', '\\node (C) at (0.9,-0.6) {$C$};', '\\draw[-{Stealth}, draw=__COLOR__] (A) -- node[left] {$f$} (B);', '\\draw[-{Stealth}, draw=__COLOR__] (A) -- node[right] {$g$} (C);', '\\draw[-{Stealth}, draw=__COLOR__] (B) -- node[below] {$h$} (C);']],
    ['math-venn', 'Math', 'Venn diagram', 'Two-set overlap', 'flow', [], ['\\draw[draw=__COLOR__] (0,0) circle (0.75);', '\\draw[draw=__COLOR__] (0.75,0) circle (0.75);', '\\node at (-0.25,0) {$A$};', '\\node at (1.0,0) {$B$};']],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.4, y: 1 },
    width: 3.6,
    height: 2.2,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    [
      'circuit-wheatstone',
      'Circuit',
      'Wheatstone bridge',
      'Four-resistor measurement bridge',
      'circuit',
      ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R_1$] (1.4,1.1) to[R,l=$R_2$] (2.8,0) to[R,l=$R_4$] (1.4,-1.1) to[R,l=$R_3$] (0,0);', '\\draw[draw=__COLOR__, line width=0.55pt] (1.4,1.1) -- (1.4,-1.1);', '\\node[right] at (2.9,0) {$V_o$};'],
    ],
    [
      'circuit-rlc-series',
      'Circuit',
      'RLC series',
      'Series resistor inductor capacitor',
      'circuit',
      ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (1.2,0) to[L,l=$L$] (2.4,0) to[C,l=$C$] (3.6,0);'],
    ],
    [
      'circuit-opamp-filter',
      'Circuit',
      'Op-amp filter',
      'Active RC filter sketch',
      'opamp',
      ['\\node[op amp, draw=__COLOR__, line width=0.65pt] (op) at (2,-0.6) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (op.-);', '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) to[C,l=$C$] ++(0,-1.1) node[ground] {};', '\\draw[draw=__COLOR__, line width=0.65pt] (op.out) -- ++(0.8,0) node[right] {$v_o$};', '\\draw[draw=__COLOR__, line width=0.65pt] (op.+) -- ++(-0.3,0) node[ground] {};'],
    ],
    [
      'circuit-differential-pair',
      'Circuit',
      'Differential pair',
      'Two-transistor analog pair',
      'differential-pair',
      ['\\node[npn, draw=__COLOR__, line width=0.65pt] (q1) at (0,0) {};', '\\node[npn, draw=__COLOR__, line width=0.65pt] (q2) at (1.8,0) {};', '\\draw[draw=__COLOR__, line width=0.55pt] (q1.E) -- (0.9,-0.9) -- (q2.E);', '\\draw[draw=__COLOR__, line width=0.55pt] (0.9,-0.9) to[I,l=$I_T$] (0.9,-2.0);'],
    ],
    [
      'logic-mux',
      'Logic',
      'MUX 2:1',
      'Multiplexer block',
      'gate',
      ['\\node[trapezium, trapezium left angle=70, trapezium right angle=110, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.2cm, minimum height=1.4cm] (m) at (0,0) {MUX};', '\\draw[draw=__COLOR__] (-1.1,0.35) -- (m.170) node[left] {$a$};', '\\draw[draw=__COLOR__] (-1.1,-0.35) -- (m.190) node[left] {$b$};', '\\draw[draw=__COLOR__] (m.east) -- ++(0.8,0) node[right] {$y$};'],
      ['shapes.geometric'],
    ],
    [
      'logic-flipflop',
      'Logic',
      'D flip-flop',
      'Sequential logic block',
      'gate',
      ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.35cm, minimum height=1.25cm, align=center] (ff) at (0,0) {D\\\\Q};', '\\draw[draw=__COLOR__] (-1.0,0.25) -- (ff.west) node[left] {$D$};', '\\draw[draw=__COLOR__] (ff.east) -- ++(0.8,0) node[right] {$Q$};', '\\draw[draw=__COLOR__] (-1.0,-0.35) -- ++(0.45,0) -- ++(0.18,0.16) -- ++(0.18,-0.16);'],
      [],
    ],
    [
      'logic-full-adder',
      'Logic',
      'Full adder',
      'Adder with carry',
      'gate',
      ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.6cm, minimum height=1.2cm] (a) at (0,0) {$\\Sigma$};', '\\draw[draw=__COLOR__] (-1.0,0.35) -- (a.west) node[left] {$x$};', '\\draw[draw=__COLOR__] (-1.0,0) -- (a.west) node[left] {$y$};', '\\draw[draw=__COLOR__] (-1.0,-0.35) -- (a.west) node[left] {$c_i$};', '\\draw[draw=__COLOR__] (a.east) -- ++(0.8,0.25) node[right] {$s$};', '\\draw[draw=__COLOR__] (a.east) -- ++(0.8,-0.25) node[right] {$c_o$};'],
      [],
    ],
  ].map(([id, group, title, description, preview, snippet, libraries = []]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.7, y: 1.3 },
    width: 4.1,
    height: 2.5,
    stroke: '#111111',
    fill: 'none',
    fillOpacity: 0.18,
    preview,
    packages: group === 'Circuit' ? ['\\usepackage[american]{circuitikz}'] : ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    [
      'plot-confidence-band',
      'Plots',
      'Confidence band',
      'Line with uncertainty ribbon',
      'plot',
      ['\\begin{axis}[width=5cm,height=3.2cm,axis lines=left,xlabel={$x$},ylabel={$y$},tick label style={font=\\scriptsize}]', '  \\addplot[name path=upper, draw=none] coordinates {(0,0.5) (1,1.0) (2,1.2) (3,1.4)};', '  \\addplot[name path=lower, draw=none] coordinates {(0,0.2) (1,0.55) (2,0.75) (3,0.95)};', '  \\addplot[fill=__FILL__, fill opacity=__FILL_OPACITY__] fill between[of=upper and lower];', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,0.35) (1,0.78) (2,0.98) (3,1.18)};', '\\end{axis}'],
      ['fillbetween'],
    ],
    [
      'plot-contour',
      'Plots',
      'Contour levels',
      '2D contour map',
      'plot',
      ['\\begin{axis}[width=4.5cm,height=3.6cm,view={0}{90},axis equal image,tick label style={font=\\scriptsize}]', '  \\addplot3[contour gnuplot={levels={0.2,0.4,0.6}}, draw=__COLOR__, samples=20] {exp(-x^2-y^2)};', '\\end{axis}'],
      ['patchplots'],
    ],
    [
      'plot-surface',
      'Plots',
      'Surface plot',
      '3D mesh surface',
      'plot',
      ['\\begin{axis}[width=4.7cm,height=3.6cm,view={45}{28},tick label style={font=\\scriptsize}]', '  \\addplot3[surf, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, samples=16] {sin(deg(x))*cos(deg(y))};', '\\end{axis}'],
      [],
    ],
    [
      'stats-qq',
      'Stats',
      'Q-Q plot',
      'Quantile diagnostic plot',
      'plot',
      ['\\begin{axis}[width=4.6cm,height=3.2cm,axis lines=left,xlabel={theoretical},ylabel={sample},tick label style={font=\\scriptsize}]', '  \\addplot[only marks, mark=*, draw=__COLOR__] coordinates {(-1.6,-1.4) (-0.6,-0.55) (0,0.1) (0.6,0.65) (1.6,1.45)};', '  \\addplot[draw=__COLOR__!45, dashed] coordinates {(-1.8,-1.8) (1.8,1.8)};', '\\end{axis}'],
      [],
    ],
    [
      'stats-violin',
      'Stats',
      'Violin plot',
      'Distribution silhouette',
      'plot',
      ['\\begin{axis}[width=4cm,height=3.2cm,axis lines=left,xtick=\\empty,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__] coordinates {(0,0) (-0.22,0.5) (-0.4,1.2) (-0.2,2.0) (0,2.4) (0.2,2.0) (0.4,1.2) (0.22,0.5) (0,0)} -- cycle;', '\\end{axis}'],
      [],
    ],
    [
      'plot-small-multiples',
      'Plots',
      'Small multiples',
      'Three aligned panels',
      'plot',
      ['\\begin{groupplot}[group style={group size=3 by 1,horizontal sep=0.35cm}, width=2.2cm, height=2.0cm, tick label style={font=\\tiny}]', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,0) (1,1)};', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,1) (1,0.4)};', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,0.4) (1,0.9)};', '\\end{groupplot}'],
      ['groupplots'],
    ],
  ].map(([id, group, title, description, preview, snippet, pgfplotsLibraries = []]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -2, y: 2 },
    width: 5,
    height: 3.4,
    stroke: '#111111',
    fill: '#dbeafe',
    fillOpacity: 0.2,
    preview,
    packages: ['\\usepackage{pgfplots}'],
    libraries: ['patterns'],
    pgfplotsLibraries,
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet,
  })),
  ...[
    ['uml-class', 'UML', 'Class box', 'Class with fields and methods', 'matrix', ['positioning'], ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=2.4cm, align=left] (c) at (0,0) {\\textbf{Model}\\\\\\hline + weights\\\\ + train()};']],
    ['uml-sequence', 'UML', 'Sequence diagram', 'Two lifelines and messages', 'flow', ['arrows.meta'], ['\\node (a) at (0,0) {Client}; \\node (b) at (2.4,0) {Server};', '\\draw[draw=__COLOR__!45] (a) -- ++(0,-2.0); \\draw[draw=__COLOR__!45] (b) -- ++(0,-2.0);', '\\draw[-{Stealth}, draw=__COLOR__] (0,-0.55) -- node[above] {request} (2.4,-0.55);', '\\draw[-{Stealth}, draw=__COLOR__, dashed] (2.4,-1.25) -- node[below] {reply} (0,-1.25);']],
    ['uml-usecase', 'UML', 'Use case', 'Actor and use-case bubbles', 'flow', [], ['\\node[circle, draw=__COLOR__, minimum size=0.35cm] (head) at (0,0.35) {};', '\\draw[draw=__COLOR__] (0,0.18) -- (0,-0.65) (-0.45,-0.15) -- (0.45,-0.15) (-0.35,-1.1) -- (0,-0.65) -- (0.35,-1.1);', '\\node[ellipse, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=2.1cm] at (2.3,-0.25) {Train model};']],
    ['dl-attention-head', 'ML / DL', 'Attention head', 'Q K V into attention', 'flow', ['arrows.meta', 'positioning'], ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (q) at (0,0.7) {$Q$};', '\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (k) at (0,0) {$K$};', '\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (v) at (0,-0.7) {$V$};', '\\node[circle, draw=__COLOR__, minimum size=0.9cm, right=1.4cm of k] (a) {$\\alpha$};', '\\draw[-{Stealth}, draw=__COLOR__] (q) -- (a); \\draw[-{Stealth}, draw=__COLOR__] (k) -- (a); \\draw[-{Stealth}, draw=__COLOR__] (v) -- (a);', '\\draw[-{Stealth}, draw=__COLOR__] (a) -- ++(1.0,0) node[right] {$z$};']],
    ['dl-unet', 'ML / DL', 'U-Net', 'Encoder decoder with skips', 'network', ['arrows.meta', 'positioning'], ['\\foreach \\i/\\h in {0/1.3,1/1.0,2/0.7} \\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, minimum width=0.45cm, minimum height=\\h cm] (e\\i) at (\\i*0.7,-\\i*0.25) {};', '\\foreach \\i/\\h in {0/0.7,1/1.0,2/1.3} \\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, minimum width=0.45cm, minimum height=\\h cm] (d\\i) at (2.8+\\i*0.7,-0.5+\\i*0.25) {};', '\\draw[-{Stealth}, draw=__COLOR__] (e2) -- (d0);', '\\draw[draw=__COLOR__!45, dashed] (e0) -- (d2); \\draw[draw=__COLOR__!45, dashed] (e1) -- (d1);']],
    ['dl-rnn-cell', 'ML / DL', 'RNN cell', 'Recurrent hidden state', 'flow', ['arrows.meta'], ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.2cm, minimum height=0.8cm] (h) at (0,0) {$h_t$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1.0,0) -- (h) node[midway, above] {$x_t$};', '\\draw[-{Stealth}, draw=__COLOR__] (h) -- ++(1.1,0) node[right] {$y_t$};', '\\draw[-{Stealth}, draw=__COLOR__] (h.north) to[out=120,in=60,looseness=5] (h.north);']],
    ['dl-gan', 'ML / DL', 'GAN diagram', 'Generator discriminator flow', 'flow', ['arrows.meta', 'positioning'], ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (z) at (0,0) {$z$};', '\\node[draw=__COLOR__, right=0.7cm of z] (g) {G};', '\\node[draw=__COLOR__, right=0.7cm of g] (d) {D};', '\\draw[-{Stealth}, draw=__COLOR__] (z) -- (g) -- node[above] {$\\hat{x}$} (d);', '\\draw[-{Stealth}, draw=__COLOR__, dashed] (d) -- ++(0.9,0) node[right] {real?};']],
    ['dl-embedding', 'ML / DL', 'Embedding table', 'Token embedding lookup', 'matrix', ['matrix', 'arrows.meta'], ['\\matrix[matrix of nodes, draw=__COLOR__, nodes={minimum width=0.45cm, minimum height=0.35cm}, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (e) at (0,0) { 0.2 & -0.1 & 0.7 \\\\ 0.8 & 0.3 & -0.4 \\\\ };', '\\draw[-{Stealth}, draw=__COLOR__] (-1.3,0) node[left] {token} -- (e.west);']],
    ['geometry-polygon', 'Geometry', 'Polygon mesh', 'Labeled polygon', 'flow', [], ['\\coordinate (A) at (0,0); \\coordinate (B) at (1.2,0.35); \\coordinate (C) at (0.9,1.2); \\coordinate (D) at (-0.35,0.9);', '\\draw[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__] (A) -- (B) -- (C) -- (D) -- cycle;', '\\draw[draw=__COLOR__!45] (A) -- (C) (B) -- (D);']],
    ['geometry-bezier', 'Geometry', 'Bezier curve', 'Control points and curve', 'flow', [], ['\\draw[draw=__COLOR__!35, dashed] (0,0) -- (0.8,1.1) -- (1.8,-0.4) -- (2.6,0.8);', '\\draw[draw=__COLOR__, line width=0.75pt] (0,0) .. controls (0.8,1.1) and (1.8,-0.4) .. (2.6,0.8);', '\\foreach \\p in {(0,0),(0.8,1.1),(1.8,-0.4),(2.6,0.8)} \\fill[__COLOR__] \\p circle (1.2pt);']],
    ['geometry-coordinate-grid', 'Geometry', 'Coordinate grid', 'Axes with points', 'flow', ['arrows.meta'], ['\\draw[step=0.5, draw=__COLOR__!18] (-1,-1) grid (2,1.5);', '\\draw[-{Stealth}, draw=__COLOR__] (-1.1,0) -- (2.1,0) node[right] {$x$};', '\\draw[-{Stealth}, draw=__COLOR__] (0,-1.1) -- (0,1.6) node[above] {$y$};', '\\fill[__COLOR__] (1,0.8) circle (1.5pt) node[above right] {$p$};']],
    ['annotation-callout-arrow', 'Annotation', 'Callout arrow', 'Note box with pointer', 'flow', ['arrows.meta'], ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, align=left, inner sep=4pt] (n) at (0,0) {important\\\\region};', '\\draw[-{Stealth}, draw=__COLOR__] (n.east) -- ++(1.1,-0.55);']],
    ['annotation-highlight', 'Annotation', 'Highlight band', 'Translucent emphasized area', 'flow', [], ['\\fill[__FILL__, fill opacity=__FILL_OPACITY__] (0,0) rectangle (2.4,0.5);', '\\draw[draw=__COLOR__, line width=0.65pt] (0,-0.25) -- (2.4,0.75);', '\\node at (1.2,0.25) {$\\mathcal{R}$};']],
    ['paper-multi-panel', 'Paper',
      'Multi-panel figure',
      'A B C labeled panels',
      'flow',
      [],
      ['\\foreach \\x/\\lab in {0/A,1.6/B,3.2/C} {', '  \\draw[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__] (\\x,0) rectangle ++(1.25,-0.9);', '  \\node[anchor=north west, font=\\bfseries] at (\\x+0.05,-0.05) {\\lab};', '}'],
    ],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.6, y: 1.4 },
    width: 4.8,
    height: 2.8,
    stroke: '#111111',
    fill: '#dbeafe',
    fillOpacity: 0.18,
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    ['circuit-controlled-vsource', 'Circuit', 'Controlled voltage source', 'Dependent source', 'source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[cV,l=$g v_x$] (2.2,0);']],
    ['circuit-current-source-i0', 'Circuit', 'Current source I0', 'Two-terminal current source', 'current-source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[I,l=$I_0$] (2.2,0);']],
    ['circuit-transformer', 'Circuit', 'Transformer', 'Coupled inductors', 'inductor', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[L,l=$L_1$] (0,-1.4);', '\\draw[draw=__COLOR__, line width=0.65pt] (1.5,0) to[L,l=$L_2$] (1.5,-1.4);', '\\draw[draw=__COLOR__!45] (0.65,0.1) -- (0.65,-1.5) (0.85,0.1) -- (0.85,-1.5);']],
    ['circuit-nmos-labeled', 'Circuit', 'NMOS labeled', 'MOSFET transistor with terminals', 'nmos', ['\\node[nmos, draw=__COLOR__, line width=0.65pt] (m) at (0,0) {};', '\\draw[draw=__COLOR__] (m.G) -- ++(-0.7,0) node[left] {$g$};', '\\draw[draw=__COLOR__] (m.D) -- ++(0,0.55) node[above] {$d$};', '\\draw[draw=__COLOR__] (m.S) -- ++(0,-0.55) node[below] {$s$};']],
    ['circuit-bjt', 'Circuit', 'NPN BJT', 'Bipolar transistor', 'npn', ['\\node[npn, draw=__COLOR__, line width=0.65pt] (q) at (0,0) {};', '\\draw[draw=__COLOR__] (q.B) -- ++(-0.7,0) node[left] {$b$};', '\\draw[draw=__COLOR__] (q.C) -- ++(0,0.55) node[above] {$c$};', '\\draw[draw=__COLOR__] (q.E) -- ++(0,-0.55) node[below] {$e$};']],
    ['circuit-spst-switch', 'Circuit', 'SPST switch', 'Open switch', 'switch', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[ospst,l=$S$] (2.2,0);']],
    ['circuit-port', 'Circuit', 'RF port', 'Port reference', 'port', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[generic,l=$Z_0$] (1.4,0);', '\\node[draw=__COLOR__, circle, inner sep=1.5pt] at (0,0) {};']],
    ['circuit-transmission-line', 'Circuit', 'Transmission line', 'Distributed line', 'transmission-line', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[tline,l=$Z_0,\\ell$] (2.8,0);']],
    ['circuit-voltmeter', 'Circuit', 'Voltmeter', 'Voltage probe meter', 'voltmeter', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[voltmeter,l=$V$] (2.2,0);']],
    ['circuit-ammeter', 'Circuit', 'Ammeter', 'Current probe meter', 'ammeter', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[ammeter,l=$I$] (2.2,0);']],
    ['circuit-vcvs', 'Circuit', 'VCVS', 'Voltage controlled source', 'controlled-source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[american controlled voltage source,l=$A v_i$] (2.2,0);']],
    ['circuit-differential-probe', 'Circuit', 'Differential probe', 'Two terminal measurement', 'diff-probe', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (0.55,0);', '\\node[circle, draw=__COLOR__, minimum size=.55cm] at (0.9,0) {$+$};', '\\node[circle, draw=__COLOR__, minimum size=.55cm] at (1.55,0) {$-$};', '\\draw[draw=__COLOR__, line width=0.65pt] (1.9,0) -- (2.45,0);']],
    [
      'circuit-inverting-amplifier',
      'Circuit',
      'Inverting op-amp',
      'Classic inverting amplifier',
      'opamp',
      [
        '\\node[op amp, draw=__COLOR__, line width=0.65pt] (op) at (2,0) {};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (-1,0.35) node[left] {__INPUT_LABEL__} to[R,l=__COMPONENT_1__] (op.-);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.+) -- ++(0,-.75) node[ground] {__GROUND_LABEL__};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.out) -- ++(.8,0) node[right] {__OUTPUT_LABEL__};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) |- ++(.35,1.0) to[R,l=__COMPONENT_2__] ++(2.1,0) -| (op.out);',
      ],
    ],
    [
      'circuit-opamp-lowpass',
      'Circuit',
      'Active low-pass',
      'Inverting RC low-pass filter',
      'opamp',
      [
        '\\node[op amp, draw=__COLOR__, line width=0.65pt] (op) at (2,0) {};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (-1,0.35) node[left] {__INPUT_LABEL__} to[R,l=__COMPONENT_1__] (op.-);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.+) -- ++(0,-.75) node[ground] {__GROUND_LABEL__};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.out) -- ++(.8,0) node[right] {__OUTPUT_LABEL__};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) |- ++(.35,1.05) to[R,l=__COMPONENT_2__] ++(2.1,0) -| (op.out);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) |- ++(.35,1.65) to[C,l=__COMPONENT_3__] ++(2.1,0) -| (op.out);',
      ],
    ],
    [
      'circuit-common-emitter',
      'Circuit',
      'Common emitter',
      'BJT voltage amplifier stage',
      'npn',
      [
        '\\node[npn, draw=__COLOR__, line width=0.65pt] (q) at (1.2,0) {};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (-1,0) node[left] {$v_i$} to[C,l=$C_{in}$] (q.B);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (q.C) to[R,l=$R_C$] ++(0,1.25) node[vcc] {$V_{CC}$};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (q.E) to[R,l=$R_E$] ++(0,-1.1) node[ground] {};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (q.C) to[C,l=$C_o$] ++(1.45,0) node[right] {$v_o$};',
        '\\draw[draw=__COLOR__, line width=0.55pt] (q.B) to[R,l_=$R_B$] ++(0,-1.0) node[ground] {};',
      ],
    ],
    [
      'circuit-rlc-parallel',
      'Circuit',
      'Parallel RLC tank',
      'Resonant shunt network',
      'circuit',
      [
        '\\draw[draw=__COLOR__, line width=0.65pt] (-.8,0) node[left] {$v$} -- (0,0);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (2.8,0);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (0,-1.8) -- (2.8,-1.8) node[ground] {};',
        '\\draw[draw=__COLOR__, line width=0.65pt] (.35,0) to[R,l=$R$] (.35,-1.8);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (1.4,0) to[L,l=$L$] (1.4,-1.8);',
        '\\draw[draw=__COLOR__, line width=0.65pt] (2.45,0) to[C,l=$C$] (2.45,-1.8);',
      ],
    ],
    [
      'telecom-ofdm-transmitter',
      'Telecom',
      'OFDM transmitter',
      'Bits to RF OFDM waveform',
      'flow',
      [
        '\\node[draw=__COLOR__, __FILL_STYLE__, minimum width=.85cm, minimum height=.48cm] (bits) at (0,0) {$b_k$};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of bits, minimum width=.9cm, minimum height=.48cm] (map) {QAM};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of map, minimum width=.85cm, minimum height=.48cm] (sp) {S/P};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of sp, minimum width=.9cm, minimum height=.48cm] (ifft) {IFFT};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of ifft, minimum width=.85cm, minimum height=.48cm] (cp) {CP};',
        '\\node[circle, draw=__COLOR__, right=.55cm of cp, minimum size=.62cm] (mix) {$\\times$};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (bits) -- (map) -- (sp) -- (ifft) -- (cp) -- (mix) -- ++(.85,0) node[right] {$s(t)$};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (mix.south) -- ++(0,-.7) node[below] {$e^{j2\\pi f_c t}$};',
      ],
      ['calc'],
    ],
    [
      'telecom-ofdm-receiver',
      'Telecom',
      'OFDM receiver',
      'RF OFDM waveform to decoded bits',
      'flow',
      [
        '\\node[circle, draw=__COLOR__, minimum size=.62cm] (mix) at (0,0) {$\\times$};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of mix, minimum width=.85cm, minimum height=.48cm] (adc) {ADC};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of adc, minimum width=.85cm, minimum height=.48cm] (sync) {sync};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of sync, minimum width=.9cm, minimum height=.48cm] (rmcp) {-CP};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of rmcp, minimum width=.9cm, minimum height=.48cm] (fft) {FFT};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of fft, minimum width=.9cm, minimum height=.48cm] (eq) {EQ};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=.55cm of eq, minimum width=.9cm, minimum height=.48cm] (dec) {FEC};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (-.8,0) node[left] {$r(t)$} -- (mix) -- (adc) -- (sync) -- (rmcp) -- (fft) -- (eq) -- (dec) -- ++(.8,0) node[right] {$\\hat{b}_k$};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (mix.south) -- ++(0,-.7) node[below] {$e^{-j2\\pi f_c t}$};',
      ],
      ['calc'],
    ],
    [
      'telecom-awgn-channel',
      'Telecom',
      'Channel + AWGN',
      'Linear channel with additive white Gaussian noise',
      'flow',
      [
        '\\node[draw=__COLOR__, __FILL_STYLE__, minimum width=1.15cm, minimum height=.58cm] (h) at (0,0) {__CHANNEL_LABEL__};',
        '\\node[circle, draw=__COLOR__, right=.85cm of h, minimum size=.62cm] (sum) {$+$};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (-1.0,0) node[left] {__INPUT_LABEL__} -- (h) -- (sum) -- ++(1.0,0) node[right] {__OUTPUT_LABEL__};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (sum.north) -- ++(0,.72) node[above] {AWGN __NOISE_LABEL__};',
        '\\node[font=\\scriptsize, text=__COLOR__!70] at (.45,-.55) {$y(t)=h(t)*x(t)+n(t)$};',
      ],
      ['calc'],
    ],
    [
      'telecom-mimo-link',
      'Telecom',
      'MIMO link',
      'Precoded antennas through channel matrix',
      'network',
      [
        '\\node[draw=__COLOR__, __FILL_STYLE__, minimum width=1.2cm, minimum height=.62cm] (p) at (0,0) {precoder};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=1.2cm of p, minimum width=1.0cm, minimum height=1.25cm] (h) {$\\mathbf{H}$};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, right=1.2cm of h, minimum width=1.2cm, minimum height=.62cm] (e) {equalizer};',
        '\\foreach \\i/\\y in {1/.48,2/0,3/-.48} {\\draw[-{Stealth}, draw=__COLOR__, line width=.5pt] (p.east) -- ++(.55,\\y) node[midway, above, font=\\scriptsize] {$x_\\i$} -- (h.west);}',
        '\\foreach \\i/\\y in {1/.48,2/0,3/-.48} {\\draw[-{Stealth}, draw=__COLOR__, line width=.5pt] (h.east) -- ++(.55,\\y) node[midway, above, font=\\scriptsize] {$y_\\i$} -- (e.west);}',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (-.9,0) node[left] {$\\mathbf{s}$} -- (p);',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (e) -- ++(.9,0) node[right] {$\\hat{\\mathbf{s}}$};',
      ],
      ['calc'],
    ],
    [
      'rf-front-end',
      'Telecom',
      'RF front-end',
      'Antenna LNA mixer IF chain',
      'flow',
      [
        '\\draw[draw=__COLOR__, line width=.65pt] (0,-.45) -- (0,.38);',
        '\\draw[draw=__COLOR__, line width=.65pt] (0,.38) -- (-.34,.88) (0,.38) -- (.34,.88);',
        '\\node[draw=__COLOR__, __FILL_STYLE__, minimum width=.75cm, minimum height=.48cm] (lna) at (1.15,0) {LNA};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, minimum width=.75cm, minimum height=.48cm] (bpf) at (2.3,0) {BPF};',
        '\\node[circle, draw=__COLOR__, minimum size=.62cm] (mix) at (3.4,0) {$\\times$};',
        '\\node[draw=__COLOR__, __FILL_STYLE__, minimum width=.75cm, minimum height=.48cm] (if) at (4.45,0) {IF};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (.34,0) -- (lna) -- (bpf) -- (mix) -- (if) -- ++(.75,0) node[right] {__OUTPUT_LABEL__};',
        '\\draw[-{Stealth}, draw=__COLOR__, line width=.55pt] (mix.south) -- ++(0,-.7) node[below] {__CARRIER_LABEL__};',
        '\\node[font=\\scriptsize, text=__COLOR__!70] at (1.7,-.55) {$G=__GAIN_DB__\\,\\mathrm{dB}$};',
      ],
      ['calc'],
    ],
    ['telecom-transmitter-chain', 'Telecom', 'Transmitter chain', 'Source to RF output', 'flow', ['\\foreach \\x/\\t in {0/Bits,1.45/Mapper,2.9/Pulse,4.35/RF} \\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.05cm, minimum height=0.55cm] (n\\x) at (\\x,0) {\\t};', '\\draw[-{Stealth}, draw=__COLOR__] (0.55,0) -- (0.9,0) (2.0,0) -- (2.35,0) (3.45,0) -- (3.8,0);']],
    ['telecom-receiver-chain', 'Telecom', 'Receiver chain', 'RF input to bits', 'flow', ['\\foreach \\x/\\t in {0/RF,1.45/ADC,2.9/Sync,4.35/Dec} \\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.05cm, minimum height=0.55cm] (n\\x) at (\\x,0) {\\t};', '\\draw[-{Stealth}, draw=__COLOR__] (0.55,0) -- (0.9,0) (2.0,0) -- (2.35,0) (3.45,0) -- (3.8,0);']],
    ['telecom-channel', 'Telecom', 'Channel + noise', 'h(t) plus additive noise', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.35cm] (h) at (0,0) {$h(t)$};', '\\node[circle, draw=__COLOR__, right=0.9cm of h] (s) {$+$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1.0,0) -- (h) -- (s) -- ++(1,0);', '\\draw[-{Stealth}, draw=__COLOR__] (s.north) -- ++(0,0.7) node[above] {$n(t)$};'], ['arrows.meta', 'positioning']],
    ['telecom-qpsk-mod', 'Telecom', 'QPSK modulator', 'I/Q mapper block', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.6cm] (m) at (0,0) {QPSK\\\\mod};', '\\draw[-{Stealth}, draw=__COLOR__] (-1.0,0) -- (m) -- ++(1.0,0) node[right] {$s(t)$};']],
    ['telecom-qpsk-demod', 'Telecom', 'QPSK demodulator', 'I/Q decision block', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.6cm] (m) at (0,0) {QPSK\\\\demod};', '\\draw[-{Stealth}, draw=__COLOR__] (-1.0,0) -- (m) -- ++(1.0,0) node[right] {$\\hat{b}$};']],
    ['telecom-random-bits', 'Telecom', 'Random bits', 'Bit source', 'matrix', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] at (0,0) {$101101$};']],
    ['telecom-bits', 'Telecom', 'Bits', 'Serial bit stream', 'matrix', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] at (0,0) {$b_k$};']],
    ['telecom-ifft', 'Telecom', 'IFFT block', 'OFDM modulation', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.3cm] at (0,0) {IFFT};']],
    ['telecom-fft', 'Telecom', 'FFT block', 'OFDM demodulation', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.3cm] at (0,0) {FFT};']],
    ['telecom-cp', 'Telecom', 'Cyclic prefix', 'OFDM CP insertion', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.4cm] at (0,0) {CP};']],
    ['telecom-mimo-tx', 'Telecom', 'MIMO TX', 'Multiple transmit antennas', 'network', ['\\node[draw=__COLOR__] (p) at (0,0) {precoder};', '\\foreach \\i in {0,1,2} \\draw[-{Stealth}, draw=__COLOR__] (p.east) -- ++(0.8,{0.45-0.45*\\i}) node[right] {$x_\\i$};']],
    ['telecom-mimo-channel', 'Telecom', 'MIMO channel', 'Channel matrix H', 'matrix', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.3cm] at (0,0) {$\\mathbf{H}$};']],
    ['telecom-mimo-rx', 'Telecom', 'MIMO RX', 'Equalizer receiver', 'network', ['\\node[draw=__COLOR__] (e) at (0,0) {equalizer};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (e) -- ++(1,0) node[right] {$\\hat{s}$};']],
    ['telecom-antenna', 'Telecom', 'Antenna', 'Radiating element', 'flow', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,-0.6) -- (0,0.45);', '\\draw[draw=__COLOR__] (0,0.45) -- (-0.45,1.0) (0,0.45) -- (0.45,1.0);', '\\draw[draw=__COLOR__!45] (-0.75,0.8) arc (140:220:0.5) (0.75,0.8) arc (40:-40:0.5);']],
    ['telecom-mixer', 'Telecom', 'Mixer', 'RF frequency conversion', 'flow', ['\\node[circle, draw=__COLOR__, minimum size=0.75cm] (m) at (0,0) {$\\times$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (m) -- ++(1,0);', '\\draw[-{Stealth}, draw=__COLOR__] (0,-1) -- (m) node[midway,right] {LO};']],
    ['telecom-filter', 'Telecom', 'Filter', 'Bandpass block', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.3cm] (f) at (0,0) {BPF};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (f) -- ++(1,0);']],
    ['telecom-link-budget', 'Telecom', 'Link budget', 'Compact budget table', 'matrix', ['\\matrix[matrix of nodes, draw=__COLOR__, nodes={anchor=west}, column sep=0.3cm] at (0,0) { Tx & 20 dBm \\\\ Path & -102 dB \\\\ Rx & -82 dBm \\\\ };']],
    ['telecom-pll', 'Telecom', 'PLL loop', 'Phase detector, loop filter, VCO', 'flow', ['\\foreach \\x/\\t in {0/PD,1.35/LF,2.7/VCO} \\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=.85cm] (n\\x) at (\\x,0) {\\t};', '\\draw[-{Stealth}, draw=__COLOR__] (-.75,0) -- (n0) -- (n1.35) -- (n2.7) -- ++(.9,0);', '\\draw[-{Stealth}, draw=__COLOR__] (3.25,-.35) |- (0,-.9) -| (n0.south);']],
    ['telecom-superhet', 'Telecom', 'Superhet receiver', 'RF mixer IF detector chain', 'flow', ['\\foreach \\x/\\t in {0/RF,1.25/Mixer,2.5/IF,3.75/Det} \\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=.9cm] (n\\x) at (\\x,0) {\\t};', '\\draw[-{Stealth}, draw=__COLOR__] (-.8,0) -- (n0) -- (n1.25) -- (n2.5) -- (n3.75) -- ++(.8,0);', '\\draw[-{Stealth}, draw=__COLOR__] (1.25,-.95) node[below] {LO} -- (n1.25);']],
    ['telecom-matched-filter', 'Telecom', 'Matched filter RX', 'Filter and sampler receiver', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (h) at (0,0) {$h^*(-t)$};', '\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, right=1cm of h] (s) {sample};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (h) -- (s) -- ++(1,0);'], ['positioning']],
    ['telecom-delay-block', 'Telecom', 'Delay z^-1', 'Discrete-time delay block', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1cm] (z) at (0,0) {$z^{-1}$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (z) -- ++(1,0);']],
    ['telecom-transfer-block', 'Telecom', 'Transfer H(z)', 'System transfer function', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.2cm] (h) at (0,0) {$H(z)$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (h) -- ++(1,0);']],
    ['telecom-feedback-loop', 'Telecom', 'Feedback loop', 'Closed-loop signal flow', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (g) at (0,0) {$G(s)$};', '\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, below=.9cm of g] (h) {$H(s)$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (g) -- ++(1,0);', '\\draw[-{Stealth}, draw=__COLOR__] (g.east) |- (h.east);', '\\draw[-{Stealth}, draw=__COLOR__] (h.west) -| (-.8,0);'], ['positioning']],
    ['rf-amplifier', 'Telecom', 'RF amplifier', 'Gain triangle block', 'flow', ['\\draw[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, line width=.65pt] (0,-.55) -- (0,.55) -- (1.2,0) -- cycle;', '\\draw[-{Stealth}, draw=__COLOR__] (-.8,0) -- (0,0);', '\\draw[-{Stealth}, draw=__COLOR__] (1.2,0) -- ++(.8,0);', '\\node at (.45,0) {$G$};']],
    ['rf-attenuator', 'Telecom', 'Attenuator', 'Pad or loss block', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.25cm] (a) at (0,0) {$-L$ dB};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (a) -- ++(1,0);']],
    ['rf-coupler', 'Telecom', 'Directional coupler', 'Coupled RF ports', 'flow', ['\\draw[draw=__COLOR__, line width=.65pt] (-1,0) -- (1,0);', '\\draw[draw=__COLOR__, line width=.65pt] (-.8,-.55) -- (.8,-.55);', '\\draw[-{Stealth}, draw=__COLOR__] (.15,-.2) -- (.65,-.45);', '\\node[font=\\scriptsize] at (0,.35) {coupler};']],
    ['rf-splitter', 'Telecom', 'Power splitter', 'One-to-two RF split', 'flow', ['\\node[circle, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (s) at (0,0) {$\\Sigma$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (s);', '\\draw[-{Stealth}, draw=__COLOR__] (s.east) -- ++(.9,.45);', '\\draw[-{Stealth}, draw=__COLOR__] (s.east) -- ++(.9,-.45);']],
    ['rf-sparameter', 'Telecom', 'S-parameter block', 'Two-port network', 'matrix', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.5cm, minimum height=.85cm] (s) at (0,0) {$\\mathbf{S}$};', '\\draw[draw=__COLOR__] (-1,0.25) -- (s.west);', '\\draw[draw=__COLOR__] (s.east) -- ++(1,0.25);', '\\node[font=\\scriptsize] at (-.8,.55) {$a_1$};', '\\node[font=\\scriptsize] at (.9,.55) {$b_2$};']],
    ['rf-waveguide', 'Telecom', 'Waveguide', 'Rectangular waveguide section', 'flow', ['\\draw[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, line width=.65pt] (-1,-.35) rectangle (1,.35);', '\\draw[draw=__COLOR__!55] (-.75,-.35) -- (-.55,.35) (.15,-.35) -- (.35,.35);', '\\draw[-{Stealth}, draw=__COLOR__] (-1.45,0) -- (-1,0);', '\\draw[-{Stealth}, draw=__COLOR__] (1,0) -- (1.45,0);']],
    ['rf-combiner', 'Telecom', 'Power combiner', 'Two-to-one RF combine', 'flow', ['\\node[circle, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1] (s) at (0,0) {$\\Sigma$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,.45) -- (s.west);', '\\draw[-{Stealth}, draw=__COLOR__] (-1,-.45) -- (s.west);', '\\draw[-{Stealth}, draw=__COLOR__] (s) -- ++(1,0);']],
    ['rf-circulator', 'Telecom', 'Circulator', 'Three-port RF circulator', 'flow', ['\\node[circle, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum size=1cm] (c) at (0,0) {};', '\\draw[-{Stealth}, draw=__COLOR__] (120:.28) arc (120:-180:.28);', '\\draw[draw=__COLOR__] (c.north) -- ++(0,.55) node[above] {1};', '\\draw[draw=__COLOR__] (c.south east) -- ++(.48,-.3) node[right] {2};', '\\draw[draw=__COLOR__] (c.south west) -- ++(-.48,-.3) node[left] {3};']],
    ['rf-isolator', 'Telecom', 'Isolator', 'One-way RF element', 'flow', ['\\node[draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__, text opacity=1, minimum width=1.15cm] (i) at (0,0) {ISO};', '\\draw[-{Stealth}, draw=__COLOR__] (-1,0) -- (i) -- ++(1,0);', '\\draw[draw=__COLOR__!55] (.35,-.35) -- (-.35,.35);']],
    ['plot-spectrum', 'Plots', 'Spectrum plot', 'Frequency spectrum', 'plot', ['\\begin{axis}[width=5cm,height=3cm,axis lines=left,xlabel={frequency $f/f_s$},ylabel={PSD (dB)},grid=major,minor tick num=1,tick label style={font=\\scriptsize}]', '  \\addplot[draw=none, fill=__FILL__, fill opacity=__FILL_OPACITY__] coordinates {(-2,-55) (-1.3,-26) (-.5,-8) (0,-3) (.5,-8) (1.3,-26) (2,-55)} \\closedcycle;', '  \\addplot[draw=__COLOR__, line width=.7pt, smooth] coordinates {(-2,-55) (-1.3,-26) (-.5,-8) (0,-3) (.5,-8) (1.3,-26) (2,-55)};', '\\end{axis}']],
    ['plot-constellation', 'Plots', 'Constellation', 'I/Q symbol points', 'plot', ['\\begin{axis}[width=3.7cm,height=3.7cm,axis lines=middle,axis equal image,xlabel={$I$},ylabel={$Q$},xmin=-1.6,xmax=1.6,ymin=-1.6,ymax=1.6,grid=both,tick label style={font=\\scriptsize}]', '  \\addplot[only marks, mark=*, mark size=2pt, draw=__COLOR__, fill=__FILL__, fill opacity=__FILL_OPACITY__] coordinates {(-1,-1) (-1,1) (1,-1) (1,1)};', '  \\draw[draw=__COLOR__!35, dashed] (axis cs:-1.35,0) -- (axis cs:1.35,0) (axis cs:0,-1.35) -- (axis cs:0,1.35);', '\\end{axis}']],
    ['plot-ber', 'Plots', 'BER curve', 'Semilog BER plot', 'plot', ['\\begin{semilogyaxis}[width=4.8cm,height=3.2cm,axis lines=left,xlabel={$E_b/N_0$ (dB)},ylabel={BER},grid=major,ymin=1e-6,ymax=1,tick label style={font=\\scriptsize},legend pos=south west]', '  \\addplot[draw=__COLOR__, mark=*, line width=.7pt] coordinates {(0,1e-1) (4,2e-2) (8,2e-3) (12,1e-5)};', '  \\addlegendentry{coded}', '  \\addplot[draw=__COLOR__!45, dashed, mark=o] coordinates {(0,2e-1) (4,6e-2) (8,1.1e-2) (12,7e-4)};', '  \\addlegendentry{uncoded}', '\\end{semilogyaxis}']],
    ['plot-eye', 'Plots', 'Eye diagram', 'Overlaid symbol traces', 'plot', ['\\begin{axis}[width=4.5cm,height=2.8cm,axis lines=left,xlabel={time (UI)},ylabel={amplitude},xmin=0,xmax=2,grid=major,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__!45, smooth] coordinates {(0,-1) (.25,-.2) (.5,1) (.75,.15) (1,-1) (1.25,-.2) (1.5,1) (1.75,.15) (2,-1)};', '  \\addplot[draw=__COLOR__, smooth] coordinates {(0,1) (.25,.25) (.5,-1) (.75,-.2) (1,1) (1.25,.25) (1.5,-1) (1.75,-.2) (2,1)};', '  \\draw[draw=__COLOR__!35, dashed] (axis cs:.5,-1.15) -- (axis cs:.5,1.15) (axis cs:1.5,-1.15) -- (axis cs:1.5,1.15);', '\\end{axis}']],
    ['plot-spectrogram', 'Plots', 'Spectrogram heatmap', 'Time-frequency matrix', 'plot', ['\\begin{axis}[width=4.8cm,height=3.2cm,xlabel={time},ylabel={frequency},view={0}{90},colorbar,colormap/viridis,tick label style={font=\\scriptsize}]', '  \\addplot3[surf, shader=interp, mesh/rows=3] coordinates {(0,0,0.1) (1,0,0.8) (2,0,0.2) (0,1,0.2) (1,1,1) (2,1,0.4) (0,2,0.1) (1,2,0.6) (2,2,0.9)};', '\\end{axis}'], [], ['colormaps']],
    ['plot-frequency-response', 'Plots', 'Frequency response', 'Magnitude and phase axis', 'plot', ['\\begin{axis}[width=4.8cm,height=3.2cm,axis lines=left,xlabel={frequency $\\omega$},ylabel={$|H(j\\omega)|$ (dB)},xmode=log,grid=major,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, line width=.7pt, smooth] coordinates {(.1,-28) (.3,-12) (1,-1) (3,-3) (10,-18)};', '  \\draw[draw=__COLOR__!40, dashed] (axis cs:.1,-3) -- (axis cs:10,-3);', '\\end{axis}']],
    ['plot-impulse-response', 'Plots', 'Impulse response', 'Discrete stem plot', 'plot', ['\\begin{axis}[width=4.8cm,height=3.2cm,axis lines=left,xlabel={$n$},ylabel={$h[n]$},grid=major,tick label style={font=\\scriptsize}]', '  \\addplot[ycomb, draw=__COLOR__, mark=*, line width=.65pt] coordinates {(0,1) (1,.55) (2,.3) (3,.16) (4,.08)};', '\\end{axis}']],
  ].map(([id, group, title, description, preview, snippet, libraries = [], pgfplotsLibraries = []]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.8, y: 1.2 },
    width: group === 'Plots' ? 5 : 3.8,
    height: group === 'Plots' ? 3.2 : 2.1,
    stroke: '#111111',
    fill: '#dbeafe',
    fillOpacity: 0.18,
    preview,
    packages: group === 'Circuit' ? ['\\usepackage[american]{circuitikz}'] : group === 'Plots' ? ['\\usepackage{pgfplots}'] : ['\\usepackage{tikz}'],
    libraries: group === 'Telecom' ? ['arrows.meta', 'positioning', ...libraries] : libraries,
    pgfplotsLibraries,
    afterPreamble: group === 'Plots' ? ['\\pgfplotsset{compat=1.18}'] : [],
    snippet,
  })),
]
