export const libraryPaletteItems = [
  {
    id: 'circuit-resistor',
    group: 'Circuit',
    title: 'Resistor',
    description: 'Two-terminal resistor',
    origin: { x: -2, y: 1 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'resistor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (2.2,0);'],
  },
  {
    id: 'circuit-capacitor',
    group: 'Circuit',
    title: 'Capacitor',
    description: 'Two-terminal capacitor',
    origin: { x: -2, y: 0 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'capacitor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[C,l=$C$] (2.2,0);'],
  },
  {
    id: 'circuit-inductor',
    group: 'Circuit',
    title: 'Inductor',
    description: 'Two-terminal inductor',
    origin: { x: -2, y: -1 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'inductor',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[L,l=$L$] (2.2,0);'],
  },
  {
    id: 'circuit-diode',
    group: 'Circuit',
    title: 'Diode',
    description: 'Diode symbol',
    origin: { x: -2, y: -2 },
    width: 2.4,
    height: 0.7,
    stroke: '#111111',
    preview: 'diode',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[D,l=$D$] (2.2,0);'],
  },
  {
    id: 'circuit-source-ground',
    group: 'Circuit',
    title: 'Source + ground',
    description: 'Voltage source reference',
    origin: { x: -2, y: -3 },
    width: 2.2,
    height: 1.7,
    stroke: '#111111',
    preview: 'source',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[V,l=$V_{in}$] (0,-1.2) node[ground] {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (1.5,0);',
    ],
  },
  {
    id: 'circuit-opamp',
    group: 'Circuit',
    title: 'Op amp',
    description: 'Operational amplifier',
    origin: { x: -1.5, y: 2 },
    width: 3.2,
    height: 2.2,
    stroke: '#111111',
    preview: 'opamp',
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet: [
      '\\node[op amp, draw=__COLOR__, line width=0.65pt] (op) at (1.4,-0.8) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.-) -- ++(-0.8,0) node[left] {$v_-$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.+) -- ++(-0.8,0) node[left] {$v_+$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (op.out) -- ++(0.8,0) node[right] {$v_o$};',
    ],
  },
  {
    id: 'logic-and-gate',
    group: 'Logic',
    title: 'AND gate',
    description: 'IEC logic gate',
    origin: { x: -1.5, y: 1.5 },
    width: 2.6,
    height: 1.8,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[and gate IEC, draw=__COLOR__, logic gate inputs=nn, line width=0.65pt] (and1) at (1,-0.6) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.input 1) -- ++(-0.7,0) node[left] {$a$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.input 2) -- ++(-0.7,0) node[left] {$b$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (and1.output) -- ++(0.7,0) node[right] {$y$};',
    ],
  },
  {
    id: 'logic-not-gate',
    group: 'Logic',
    title: 'NOT gate',
    description: 'Inverter gate',
    origin: { x: -1.5, y: 0.2 },
    width: 2.4,
    height: 1.4,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      '\\node[not gate IEC, draw=__COLOR__, line width=0.65pt] (not1) at (1,-0.5) {};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (not1.input) -- ++(-0.7,0) node[left] {$x$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (not1.output) -- ++(0.7,0) node[right] {$\\bar{x}$};',
    ],
  },
  {
    id: 'plot-axis',
    group: 'Plots',
    title: 'Axis plot',
    description: 'Publication axis',
    origin: { x: -2, y: 2 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[',
      '  width=5.2cm, height=3.2cm,',
      '  axis lines=left,',
      '  xlabel={$x$}, ylabel={$f(x)$},',
      '  tick style={draw=__COLOR__},',
      '  label style={font=\\small},',
      '  tick label style={font=\\scriptsize},',
      '  every axis plot/.append style={draw=__COLOR__, line width=0.65pt}',
      ']',
      '  \\addplot[smooth] coordinates {(-2,0.2) (-1,0.7) (0,1.0) (1,0.7) (2,0.2)};',
      '\\end{axis}',
    ],
  },
  {
    id: 'plot-error-bars',
    group: 'Plots',
    title: 'Error bars',
    description: 'Data with uncertainty',
    origin: { x: -2, y: -1.5 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet: [
      '\\begin{axis}[',
      '  width=5.2cm, height=3.2cm,',
      '  axis lines=left,',
      '  xlabel={$n$}, ylabel={Score},',
      '  error bars/y dir=both, error bars/y explicit,',
      '  tick label style={font=\\scriptsize}',
      ']',
      '  \\addplot+[only marks, mark=*, draw=__COLOR__, mark options={fill=white}, error bars/.cd, y explicit]',
      '    coordinates {(1,0.42) +- (0,0.05) (2,0.56) +- (0,0.04) (3,0.63) +- (0,0.06)};',
      '\\end{axis}',
    ],
  },
  {
    id: 'automata-state',
    group: 'Automata',
    title: 'State transition',
    description: 'Two states and arrow',
    origin: { x: -1.5, y: 1.2 },
    width: 3.8,
    height: 1.7,
    stroke: '#111111',
    preview: 'automata',
    packages: ['\\usepackage{tikz}'],
    libraries: ['automata', 'positioning', 'arrows.meta'],
    snippet: [
      '\\node[state, draw=__COLOR__, line width=0.65pt] (q0) at (0,0) {$q_0$};',
      '\\node[state, draw=__COLOR__, line width=0.65pt, right=1.6cm of q0] (q1) {$q_1$};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.65pt] (q0) -- node[above] {$a$} (q1);',
    ],
  },
  {
    id: 'matrix-block',
    group: 'Math',
    title: 'Matrix block',
    description: 'Matrix of nodes',
    origin: { x: -1.4, y: 1.4 },
    width: 3.2,
    height: 2.1,
    stroke: '#111111',
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['matrix'],
    snippet: [
      '\\matrix[matrix of math nodes, left delimiter={[}, right delimiter={]}, draw=__COLOR__, inner sep=3pt] (m) at (1,-0.7) {',
      '  a_{11} & a_{12} \\\\',
      '  a_{21} & a_{22} \\\\',
      '};',
    ],
  },
  {
    id: 'commutative-square',
    group: 'Math',
    title: 'Commutative square',
    description: 'Four objects and arrows',
    origin: { x: -1.8, y: 1.8 },
    width: 3.8,
    height: 2.8,
    stroke: '#111111',
    preview: 'matrix',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning'],
    snippet: [
      '\\node (A) at (0,0) {$A$};',
      '\\node[right=1.8cm of A] (B) {$B$};',
      '\\node[below=1.2cm of A] (C) {$C$};',
      '\\node[right=1.8cm of C] (D) {$D$};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (A) -- node[above] {$f$} (B);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (A) -- node[left] {$g$} (C);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (B) -- node[right] {$h$} (D);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.6pt] (C) -- node[below] {$k$} (D);',
    ],
  },
  {
    id: 'dl-layer',
    group: 'ML / DL',
    title: 'Dense layer',
    description: 'Neural network layer pair',
    origin: { x: -1.5, y: 1.8 },
    width: 3.6,
    height: 3.4,
    stroke: '#111111',
    preview: 'network',
    packages: ['\\usepackage{tikz}'],
    libraries: ['positioning'],
    snippet: [
      '\\foreach \\i in {1,...,4} \\node[circle, draw=__COLOR__, minimum size=4.5mm, inner sep=0pt] (x\\i) at (0,-0.5*\\i) {};',
      '\\foreach \\j in {1,...,3} \\node[circle, draw=__COLOR__, minimum size=4.5mm, inner sep=0pt] (h\\j) at (1.6,-0.35-0.65*\\j) {};',
      '\\foreach \\i in {1,...,4} \\foreach \\j in {1,...,3} \\draw[draw=__COLOR__!45, line width=0.35pt] (x\\i) -- (h\\j);',
      '\\node[below=0.15cm of x4] {input};',
      '\\node[below=0.15cm of h3] {hidden};',
    ],
  },
  {
    id: 'ml-pipeline',
    group: 'ML / DL',
    title: 'Pipeline',
    description: 'Data to evaluation flow',
    origin: { x: -2.5, y: 0.8 },
    width: 5.8,
    height: 1.4,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['arrows.meta', 'positioning'],
    snippet: [
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm] (data) at (0,0) {data};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of data] (feat) {features};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of feat] (model) {model};',
      '\\node[draw=__COLOR__, minimum width=1cm, minimum height=0.45cm, right=0.6cm of model] (eval) {eval};',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (data) -- (feat);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (feat) -- (model);',
      '\\draw[-{Stealth}, draw=__COLOR__, line width=0.55pt] (model) -- (eval);',
    ],
  },
  {
    id: 'gantt-paper',
    group: 'Planning',
    title: 'Gantt bars',
    description: 'Compact project timeline',
    origin: { x: -2.4, y: 1.4 },
    width: 5.6,
    height: 2.7,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.5pt] (0,0) rectangle (4.8,-1.8);',
      '\\foreach \\x in {1,2,3,4} \\draw[draw=__COLOR__!25, line width=0.3pt] (\\x,0) -- (\\x,-1.8);',
      '\\node[anchor=east] at (-0.15,-0.35) {prep};',
      '\\node[anchor=east] at (-0.15,-0.9) {train};',
      '\\node[anchor=east] at (-0.15,-1.45) {write};',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (0.25,-0.52) rectangle (1.45,-0.18);',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (1.25,-1.07) rectangle (3.65,-0.73);',
      '\\filldraw[fill=__COLOR__!12, draw=__COLOR__, line width=0.45pt] (3.1,-1.62) rectangle (4.55,-1.28);',
    ],
  },
  {
    id: 'tree-small',
    group: 'Graph',
    title: 'Tree',
    description: 'Root with children',
    origin: { x: -1.5, y: 1.5 },
    width: 3.2,
    height: 2.5,
    stroke: '#111111',
    preview: 'tree',
    packages: ['\\usepackage{tikz}'],
    libraries: ['trees'],
    snippet: [
      '\\node[draw=__COLOR__, circle, inner sep=1.5pt] {root}',
      '  child { node[draw=__COLOR__, circle, inner sep=1.5pt] {a} }',
      '  child { node[draw=__COLOR__, circle, inner sep=1.5pt] {b} };',
    ],
  },
  {
    id: 'angle-marker',
    group: 'Geometry',
    title: 'Angle marker',
    description: 'Annotated angle',
    origin: { x: -1.2, y: 0.8 },
    width: 2.8,
    height: 1.8,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['angles', 'quotes'],
    snippet: [
      '\\coordinate (A) at (0,0);',
      '\\coordinate (B) at (1.8,0);',
      '\\coordinate (C) at (1.2,1.0);',
      '\\draw[draw=__COLOR__, line width=0.65pt] (A) -- (B) -- (C);',
      '\\pic[draw=__COLOR__, "$\\theta$", angle radius=0.45cm] {angle=A--B--C};',
    ],
  },
  {
    id: 'brace-annotation',
    group: 'Annotation',
    title: 'Brace label',
    description: 'Brace annotation',
    origin: { x: -1.4, y: 0.8 },
    width: 3.2,
    height: 1.5,
    stroke: '#111111',
    preview: 'flow',
    packages: ['\\usepackage{tikz}'],
    libraries: ['decorations.pathreplacing'],
    snippet: [
      '\\draw[draw=__COLOR__, line width=0.65pt] (0,0) -- (2.4,0);',
      '\\draw[decorate, decoration={brace, amplitude=4pt}, draw=__COLOR__, line width=0.55pt] (0,0.25) -- node[above=5pt] {$n$ samples} (2.4,0.25);',
    ],
  },
  ...[
    ['circuit-battery', 'Circuit', 'Battery', 'DC source', 'source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[battery1,l=$V$] (2.0,0);']],
    ['circuit-current-source', 'Circuit', 'Current source', 'Independent current source', 'source', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[I,l=$I$] (2.0,0);']],
    ['circuit-switch', 'Circuit', 'Switch', 'Open switch', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[normal open switch,l=$S$] (2.0,0);']],
    ['circuit-lamp', 'Circuit', 'Lamp', 'Lamp load', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[lamp,l=$L$] (2.0,0);']],
    ['circuit-led', 'Circuit', 'LED', 'Light emitting diode', 'diode', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[led,l=$D$] (2.0,0);']],
    ['circuit-zener', 'Circuit', 'Zener diode', 'Zener regulator diode', 'diode', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[zD,l=$D_z$] (2.0,0);']],
    ['circuit-npn', 'Circuit', 'NPN transistor', 'BJT transistor', 'flow', ['\\node[npn, draw=__COLOR__, line width=0.65pt] (q) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.B) -- ++(-0.6,0) node[left] {$B$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.C) -- ++(0,0.55) node[above] {$C$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.E) -- ++(0,-0.55) node[below] {$E$};']],
    ['circuit-pnp', 'Circuit', 'PNP transistor', 'BJT transistor', 'flow', ['\\node[pnp, draw=__COLOR__, line width=0.65pt] (q) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.B) -- ++(-0.6,0) node[left] {$B$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.C) -- ++(0,0.55) node[above] {$C$};', '\\draw[draw=__COLOR__, line width=0.65pt] (q.E) -- ++(0,-0.55) node[below] {$E$};']],
    ['circuit-nmos', 'Circuit', 'NMOS', 'MOS transistor', 'flow', ['\\node[nmos, draw=__COLOR__, line width=0.65pt] (m) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.G) -- ++(-0.6,0) node[left] {$G$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.D) -- ++(0,0.55) node[above] {$D$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.S) -- ++(0,-0.55) node[below] {$S$};']],
    ['circuit-pmos', 'Circuit', 'PMOS', 'MOS transistor', 'flow', ['\\node[pmos, draw=__COLOR__, line width=0.65pt] (m) at (0,0) {};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.G) -- ++(-0.6,0) node[left] {$G$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.D) -- ++(0,0.55) node[above] {$D$};', '\\draw[draw=__COLOR__, line width=0.65pt] (m.S) -- ++(0,-0.55) node[below] {$S$};']],
    ['circuit-rl-lowpass', 'Circuit', 'RL branch', 'Resistor and inductor', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (1.6,0) to[L,l=$L$] (3.2,0);']],
    ['circuit-rc-lowpass', 'Circuit', 'RC low-pass', 'Filter topology', 'circuit', ['\\draw[draw=__COLOR__, line width=0.65pt] (0,0) to[R,l=$R$] (2,0) -- (3,0);', '\\draw[draw=__COLOR__, line width=0.65pt] (2,0) to[C,l=$C$] (2,-1.3) node[ground] {};']],
  ].map(([id, group, title, description, preview, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.4, y: 1 },
    width: 3.4,
    height: 1.9,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage[american]{circuitikz}'],
    snippet,
  })),
  ...[
    ['logic-or-gate', 'OR gate', 'IEC logic gate', 'or gate IEC', 'nn'],
    ['logic-xor-gate', 'XOR gate', 'IEC logic gate', 'xor gate IEC', 'nn'],
    ['logic-nand-gate', 'NAND gate', 'IEC logic gate', 'nand gate IEC', 'nn'],
    ['logic-nor-gate', 'NOR gate', 'IEC logic gate', 'nor gate IEC', 'nn'],
    ['logic-xnor-gate', 'XNOR gate', 'IEC logic gate', 'xnor gate IEC', 'nn'],
  ].map(([id, title, description, gate, inputs]) => ({
    id,
    group: 'Logic',
    title,
    description,
    origin: { x: -1.5, y: 1.2 },
    width: 2.8,
    height: 1.7,
    stroke: '#111111',
    preview: 'gate',
    packages: ['\\usepackage{tikz}'],
    libraries: ['circuits.logic.IEC', 'positioning'],
    snippet: [
      `\\node[${gate}, draw=__COLOR__, logic gate inputs=${inputs}, line width=0.65pt] (g) at (1,-0.5) {};`,
      '\\draw[draw=__COLOR__, line width=0.65pt] (g.input 1) -- ++(-0.7,0) node[left] {$a$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (g.input 2) -- ++(-0.7,0) node[left] {$b$};',
      '\\draw[draw=__COLOR__, line width=0.65pt] (g.output) -- ++(0.7,0) node[right] {$y$};',
    ],
  })),
  ...[
    ['shape-process', 'Shapes', 'Process box', 'Rectangular process node', 'flow', ['positioning'], ['\\node[draw=__COLOR__, line width=0.6pt, minimum width=2.2cm, minimum height=0.65cm] (p) at (0,0) {process};']],
    ['shape-decision', 'Shapes', 'Decision diamond', 'Decision node', 'flow', ['shapes.geometric'], ['\\node[diamond, draw=__COLOR__, line width=0.6pt, aspect=2, inner sep=1pt] (d) at (0,0) {test};']],
    ['shape-ellipse-node', 'Shapes', 'Ellipse node', 'State or variable node', 'automata', ['shapes.geometric'], ['\\node[ellipse, draw=__COLOR__, line width=0.6pt, minimum width=1.8cm] (e) at (0,0) {$x$};']],
    ['shape-cylinder', 'Shapes', 'Cylinder', 'Database style node', 'flow', ['shapes.geometric'], ['\\node[cylinder, draw=__COLOR__, line width=0.6pt, shape border rotate=90, aspect=0.25, minimum height=1.1cm] (db) at (0,0) {data};']],
    ['shape-cloud', 'Shapes', 'Cloud', 'Cloud node', 'flow', ['shapes.symbols'], ['\\node[cloud, draw=__COLOR__, line width=0.6pt, cloud puffs=11, minimum width=2.1cm] (c) at (0,0) {cloud};']],
    ['shape-callout', 'Shapes', 'Callout', 'Annotation callout', 'flow', ['shapes.callouts'], ['\\node[rectangle callout, callout relative pointer={(0.8,-0.5)}, draw=__COLOR__, line width=0.6pt] (c) at (0,0) {note};']],
    ['shape-fit-box', 'Shapes', 'Fit box', 'Dashed grouping box', 'flow', ['fit', 'positioning'], ['\\node[draw=__COLOR__, dashed, line width=0.55pt, inner sep=6pt, fit={(0,0) (2,-1)}] (fitbox) {};']],
    ['shape-rounded-module', 'Shapes', 'Module', 'Rounded module box', 'flow', ['positioning'], ['\\node[draw=__COLOR__, rounded corners=2pt, line width=0.6pt, minimum width=2cm, minimum height=0.7cm] (m) at (0,0) {module};']],
    ['shape-table', 'Shapes', 'Small table', 'Tabular node mockup', 'matrix', ['matrix'], ['\\matrix[matrix of nodes, draw=__COLOR__, line width=0.55pt, nodes={minimum width=0.8cm, minimum height=0.35cm}] (t) at (0,0) { A & B \\\\ 1 & 2 \\\\ };']],
    ['shape-image-placeholder', 'Shapes', 'Image frame', 'Figure panel placeholder', 'flow', [], ['\\draw[draw=__COLOR__, line width=0.6pt] (0,0) rectangle (2.4,-1.4);', '\\draw[draw=__COLOR__!60, line width=0.4pt] (0,0) -- (2.4,-1.4) (0,-1.4) -- (2.4,0);']],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.2, y: 1 },
    width: 3,
    height: 2,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    ['plot-scatter', 'Scatter plot', 'Marks with trend', ['\\begin{axis}[width=5cm,height=3.2cm,axis lines=left,xlabel={$x$},ylabel={$y$},tick label style={font=\\scriptsize}]', '  \\addplot[only marks, mark=*, draw=__COLOR__] coordinates {(0,0.2) (1,0.7) (2,0.9) (3,1.6)};', '  \\addplot[draw=__COLOR__, line width=0.55pt] coordinates {(0,0.25) (3,1.45)};', '\\end{axis}']],
    ['plot-bar', 'Bar chart', 'Compact bars', ['\\begin{axis}[width=5cm,height=3.2cm,ybar,axis lines=left,symbolic x coords={A,B,C},xtick=data,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, fill=__COLOR__!15] coordinates {(A,2) (B,3.5) (C,2.8)};', '\\end{axis}']],
    ['plot-histogram', 'Histogram', 'Distribution bars', ['\\begin{axis}[width=5cm,height=3.2cm,ybar interval,axis lines=left,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, fill=__COLOR__!12] coordinates {(0,1) (1,4) (2,6) (3,3) (4,1)};', '\\end{axis}']],
    ['plot-heatmap', 'Heatmap', 'Matrix heatmap', ['\\begin{axis}[width=4.4cm,height=3.4cm,view={0}{90},colorbar,tick label style={font=\\scriptsize}]', '  \\addplot3[surf, shader=flat] coordinates {(0,0,0.1) (0,1,0.4) (1,0,0.7) (1,1,0.2)};', '\\end{axis}']],
    ['plot-boxplot', 'Box plot', 'Statistical summary', ['\\begin{axis}[width=4.8cm,height=3.2cm,boxplot/draw direction=y,axis lines=left,tick label style={font=\\scriptsize}]', '  \\addplot+[boxplot prepared={lower whisker=1, lower quartile=2, median=3, upper quartile=4, upper whisker=5}, draw=__COLOR__] coordinates {};', '\\end{axis}']],
    ['plot-semilog', 'Semilog axis', 'Logarithmic y axis', ['\\begin{semilogyaxis}[width=5cm,height=3.2cm,axis lines=left,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,1) (1,3) (2,10) (3,25)};', '\\end{semilogyaxis}']],
    ['plot-polar', 'Polar plot', 'Polar curve', ['\\begin{polaraxis}[width=4cm,height=4cm,tick label style={font=\\scriptsize}]', '  \\addplot[draw=__COLOR__, samples=120, domain=0:360] {1+0.35*cos(3*x)};', '\\end{polaraxis}'], ['polar']],
    ['plot-group', 'Group plots', 'Two aligned panels', ['\\begin{groupplot}[group style={group size=2 by 1}, width=3.2cm, height=2.6cm]', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,0) (1,1)};', '  \\nextgroupplot \\addplot[draw=__COLOR__] coordinates {(0,1) (1,0)};', '\\end{groupplot}'], ['groupplots']],
  ].map(([id, title, description, snippet, pgfplotsLibraries = []]) => ({
    id,
    group: 'Plots',
    title,
    description,
    origin: { x: -2, y: 2 },
    width: 4.8,
    height: 3.2,
    stroke: '#111111',
    preview: 'plot',
    packages: ['\\usepackage{pgfplots}'],
    pgfplotsLibraries,
    afterPreamble: ['\\pgfplotsset{compat=1.18}'],
    snippet,
  })),
  ...[
    ['graph-directed', 'Graph', 'Directed edge', 'Two nodes with edge', 'network', ['arrows.meta', 'positioning'], ['\\node[circle, draw=__COLOR__] (a) at (0,0) {$a$};', '\\node[circle, draw=__COLOR__, right=1.4cm of a] (b) {$b$};', '\\draw[-{Stealth}, draw=__COLOR__] (a) -- (b);']],
    ['graph-bipartite', 'Graph', 'Bipartite graph', 'Two node partitions', 'network', ['positioning'], ['\\foreach \\i in {1,2,3} \\node[circle, draw=__COLOR__, inner sep=1.5pt] (u\\i) at (0,-0.55*\\i) {};', '\\foreach \\j in {1,2} \\node[circle, draw=__COLOR__, inner sep=1.5pt] (v\\j) at (1.6,-0.75*\\j-0.2) {};', '\\foreach \\i in {1,2,3} \\foreach \\j in {1,2} \\draw[draw=__COLOR__!55] (u\\i) -- (v\\j);']],
    ['automata-loop', 'Automata', 'Self loop', 'State with loop', 'automata', ['automata', 'positioning', 'arrows.meta'], ['\\node[state, draw=__COLOR__] (q) at (0,0) {$q$};', '\\draw[-{Stealth}, draw=__COLOR__] (q) edge[loop above] node {$a$} (q);']],
    ['petri-basic', 'Petri', 'Petri net', 'Place transition place', 'network', ['petri', 'positioning', 'arrows.meta'], ['\\node[place, draw=__COLOR__] (p1) at (0,0) {};', '\\node[transition, draw=__COLOR__, right=1cm of p1] (t) {};', '\\node[place, draw=__COLOR__, right=1cm of t] (p2) {};', '\\draw[-{Stealth}, draw=__COLOR__] (p1) -- (t) -- (p2);']],
    ['flow-decision', 'Flow', 'Decision branch', 'Diamond branch flow', 'flow', ['arrows.meta', 'shapes.geometric', 'positioning'], ['\\node[diamond, draw=__COLOR__, aspect=2] (d) at (0,0) {ok?};', '\\node[draw=__COLOR__, below left=0.7cm and 0.7cm of d] (n) {no};', '\\node[draw=__COLOR__, below right=0.7cm and 0.7cm of d] (y) {yes};', '\\draw[-{Stealth}, draw=__COLOR__] (d) -- (n);', '\\draw[-{Stealth}, draw=__COLOR__] (d) -- (y);']],
    ['flow-swimlane', 'Flow', 'Swimlane', 'Two-lane process', 'flow', ['arrows.meta', 'positioning'], ['\\draw[draw=__COLOR__!45] (0,0) rectangle (4,-1.8);', '\\draw[draw=__COLOR__!25] (0,-0.9) -- (4,-0.9);', '\\node[draw=__COLOR__] (a) at (0.9,-0.45) {A};', '\\node[draw=__COLOR__] (b) at (3.1,-1.35) {B};', '\\draw[-{Stealth}, draw=__COLOR__] (a) -- (b);']],
    ['er-entity', 'ER', 'Entity relation', 'Entity with relationship', 'flow', ['er', 'positioning'], ['\\node[entity, draw=__COLOR__] (e1) at (0,0) {User};', '\\node[relationship, draw=__COLOR__, right=1.4cm of e1] (r) {owns};', '\\node[entity, draw=__COLOR__, right=1.4cm of r] (e2) {File};', '\\draw[draw=__COLOR__] (e1) -- (r) -- (e2);']],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.8, y: 1.3 },
    width: 4.8,
    height: 2.8,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
  ...[
    ['ml-confusion', 'ML / DL', 'Confusion matrix', '2x2 classifier matrix', 'matrix', ['matrix'], ['\\matrix[matrix of nodes, draw=__COLOR__, nodes={minimum width=0.9cm, minimum height=0.45cm}] (cm) at (0,0) { TP & FP \\\\ FN & TN \\\\ };']],
    ['ml-roc', 'ML / DL', 'ROC curve', 'Classifier ROC axis', 'plot', [], ['\\begin{axis}[width=4.5cm,height=3.2cm,axis lines=left,xlabel={FPR},ylabel={TPR},xmin=0,xmax=1,ymin=0,ymax=1]', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,0) (0.1,0.45) (0.35,0.75) (1,1)};', '  \\addplot[draw=__COLOR__!35, dashed] coordinates {(0,0) (1,1)};', '\\end{axis}'], ['\\usepackage{pgfplots}'], [], ['\\pgfplotsset{compat=1.18}']],
    ['ml-training-curve', 'ML / DL', 'Training curve', 'Loss versus epoch', 'plot', [], ['\\begin{axis}[width=4.8cm,height=3.2cm,axis lines=left,xlabel={epoch},ylabel={loss}]', '  \\addplot[draw=__COLOR__, line width=0.65pt] coordinates {(0,1.2) (1,0.7) (2,0.45) (3,0.32)};', '\\end{axis}'], ['\\usepackage{pgfplots}'], [], ['\\pgfplotsset{compat=1.18}']],
    ['dl-cnn-stack', 'ML / DL', 'CNN stack', 'Convolutional feature blocks', 'cube', ['3d', 'positioning'], ['\\draw[draw=__COLOR__, fill=__COLOR__!5] (0,0) rectangle (0.55,1.2);', '\\draw[draw=__COLOR__, fill=__COLOR__!8] (0.75,0.15) rectangle (1.25,1.05);', '\\draw[draw=__COLOR__, fill=__COLOR__!12] (1.45,0.3) rectangle (1.85,0.9);', '\\node[below] at (0.9,-0.1) {conv};']],
    ['dl-transformer', 'ML / DL', 'Transformer block', 'Attention plus MLP', 'flow', ['arrows.meta', 'positioning'], ['\\node[draw=__COLOR__, minimum width=2cm] (attn) at (0,0) {attention};', '\\node[draw=__COLOR__, minimum width=2cm, below=0.55cm of attn] (mlp) {MLP};', '\\draw[-{Stealth}, draw=__COLOR__] (attn) -- (mlp);', '\\draw[draw=__COLOR__, rounded corners] (-1.25,0.35) rectangle (1.25,-1.0);']],
    ['dl-residual', 'ML / DL', 'Residual block', 'Skip connection', 'flow', ['arrows.meta', 'positioning'], ['\\node[draw=__COLOR__] (f) at (0,0) {$F(x)$};', '\\draw[-{Stealth}, draw=__COLOR__] (-1.2,0) -- (f) -- (1.2,0);', '\\draw[-{Stealth}, draw=__COLOR__] (-1.0,0) |- (0,-0.75) -| (1.0,0);', '\\node[right] at (1.25,0) {$x+F(x)$};']],
    ['dl-autoencoder', 'ML / DL', 'Autoencoder', 'Encoder latent decoder', 'network', ['positioning'], ['\\node[draw=__COLOR__] (enc) at (0,0) {encoder};', '\\node[circle, draw=__COLOR__, right=0.7cm of enc] (z) {$z$};', '\\node[draw=__COLOR__, right=0.7cm of z] (dec) {decoder};', '\\draw[draw=__COLOR__] (enc) -- (z) -- (dec);']],
  ].map(([id, group, title, description, preview, libraries, snippet, packages = ['\\usepackage{tikz}'], pgfplotsLibraries = [], afterPreamble = []]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.8, y: 1.6 },
    width: 4.8,
    height: 3,
    stroke: '#111111',
    preview,
    packages,
    libraries,
    pgfplotsLibraries,
    afterPreamble,
    snippet,
  })),
  ...[
    ['geom-vector', 'Geometry', 'Vector', 'Arrowed vector', 'flow', ['arrows.meta'], ['\\draw[-{Stealth}, draw=__COLOR__, line width=0.65pt] (0,0) -- (2,1) node[right] {$\\mathbf{v}$};']],
    ['geom-basis', 'Geometry', 'Basis axes', 'Local coordinate frame', 'flow', ['arrows.meta'], ['\\draw[-{Stealth}, draw=__COLOR__] (0,0) -- (1.6,0) node[right] {$e_1$};', '\\draw[-{Stealth}, draw=__COLOR__] (0,0) -- (0,1.3) node[above] {$e_2$};']],
    ['geom-right-angle', 'Geometry', 'Right angle', 'Orthogonal marker', 'flow', [], ['\\draw[draw=__COLOR__] (0,0) -- (1.8,0) -- (1.8,1.1);', '\\draw[draw=__COLOR__] (1.55,0) -- (1.55,0.25) -- (1.8,0.25);']],
    ['annot-dimension', 'Annotation', 'Dimension line', 'Measured span', 'flow', ['arrows.meta'], ['\\draw[{Stealth}-{Stealth}, draw=__COLOR__, line width=0.55pt] (0,0) -- node[above] {$d$} (2.4,0);', '\\draw[draw=__COLOR__!65] (0,0.15) -- (0,-0.15) (2.4,0.15) -- (2.4,-0.15);']],
    ['annot-dashed-region', 'Annotation', 'Dashed region', 'Highlighted domain', 'flow', ['patterns'], ['\\draw[draw=__COLOR__, dashed, line width=0.55pt] (0,0) rectangle (2,-1.2);', '\\node at (1,-0.6) {$\\Omega$};']],
    ['annot-bracket', 'Annotation', 'Bracket label', 'Square bracket annotation', 'flow', ['decorations.pathreplacing'], ['\\draw[decorate, decoration={brace, mirror, amplitude=4pt}, draw=__COLOR__] (0,0) -- node[below=5pt] {window} (2.4,0);']],
    ['math-equation-node', 'Math', 'Equation node', 'Centered equation label', 'flow', [], ['\\node[draw=__COLOR__, inner sep=4pt] at (0,0) {$y = X\\beta + \\epsilon$};']],
    ['math-theorem-box', 'Math', 'Theorem box', 'Small framed statement', 'flow', [], ['\\node[draw=__COLOR__, align=left, inner sep=5pt] at (0,0) {Lemma.\\\\If $A$, then $B$.};']],
    ['math-comm-triangle', 'Math', 'Commutative triangle', 'Triangle diagram', 'network', ['arrows.meta', 'positioning'], ['\\node (A) at (0,0.9) {$A$};', '\\node (B) at (-0.9,-0.6) {$B$};', '\\node (C) at (0.9,-0.6) {$C$};', '\\draw[-{Stealth}, draw=__COLOR__] (A) -- node[left] {$f$} (B);', '\\draw[-{Stealth}, draw=__COLOR__] (A) -- node[right] {$g$} (C);', '\\draw[-{Stealth}, draw=__COLOR__] (B) -- node[below] {$h$} (C);']],
    ['math-venn', 'Math', 'Venn diagram', 'Two-set overlap', 'flow', [], ['\\draw[draw=__COLOR__] (0,0) circle (0.75);', '\\draw[draw=__COLOR__] (0.75,0) circle (0.75);', '\\node at (-0.25,0) {$A$};', '\\node at (1.0,0) {$B$};']],
  ].map(([id, group, title, description, preview, libraries, snippet]) => ({
    id,
    group,
    title,
    description,
    origin: { x: -1.4, y: 1 },
    width: 3.6,
    height: 2.2,
    stroke: '#111111',
    preview,
    packages: ['\\usepackage{tikz}'],
    libraries,
    snippet,
  })),
]
